
/* ============================================================
   PHASE 63 — GALACTIC EXPANSION
   PHASE 64 — DYNAMIC GALAXY SIMULATION
   Source-named locations use the supplied project references.
   Influence values, market shifts, control changes, generic NPCs,
   and district gameplay are original Sable Reach adaptations.
   ============================================================ */
BUILD_INFO.version='64.0.0-galactic-expansion-dynamic-galaxy';
BUILD_INFO.saveSchema=64;

Object.assign(GALAXY_HUBS_50,{
  nalHutta:{id:'nalHutta',name:'Bilbousa',world:'Nal Hutta',region:'Hutt Space · Mid Rim',summary:'The capital of the Hutt homeworld sits amid fetid swamps, kajidic estates, tightly monitored traffic, and constant political maneuvering.',source:'Lords of Nal Hutta · Nal Hutta profile',security:3,rarityMod:1,priceMod:1.08,restrictedPrice:.90,restrictedRarity:-1,nav:3,route:3,primaryFaction:'Hutts',factions:['Hutts','Guild','Empire','Local'],env:['cantina','jungle','hangar','lab'],jobs:['heist','bounty','smuggling'],services:['lodging','clinic','shipyard','cantina','market','blackmarket','guild','fixer']},
  toydaria:{id:'toydaria',name:'Toydor',world:'Toydaria',region:'Hutt Space · Mid Rim',summary:'A swamp-ringed commercial capital where royal authority, Hutt influence, merchants, and a robust Imperial customs presence all compete for leverage.',source:'Lords of Nal Hutta · Toydaria profile',security:3,rarityMod:2,priceMod:1.03,restrictedPrice:.98,restrictedRarity:0,nav:3,route:2,primaryFaction:'Local',factions:['Local','Hutts','Empire','Guild'],env:['jungle','cantina','hangar','grassland'],jobs:['smuggling','salvage','bounty'],services:['lodging','clinic','shipyard','cantina','market','guild']},
  empressTeta:{id:'empressTeta',name:'Cinnagar',world:'Empress Teta',region:'Deep Core',summary:'A planetwide metropolis, carbonite center, and Deep Core gateway where the Mining Guild and Imperial security make profitable business heavily supervised.',source:'Nexus of Power · Empress Teta / Cinnagar',security:5,rarityMod:0,priceMod:1.10,restrictedPrice:1.35,restrictedRarity:2,nav:5,route:8,primaryFaction:'Empire',factions:['Empire','Guild','Local'],env:['lab','hangar','chase','cantina'],jobs:['heist','smuggling','force'],services:['lodging','clinic','shipyard','cantina','market','fixer']},
  yavin4:{id:'yavin4',name:'Great Temple Ruins',world:'Yavin 4',region:'Outer Rim',summary:'The recently evacuated Rebel headquarters has become a dangerous ruin of abandoned infrastructure, hidden caches, jungle approaches, and Imperial interest.',source:'Star Wars Encyclopedia · Yavin 4 after the Battle of Yavin',security:3,rarityMod:3,priceMod:1.15,restrictedPrice:1.15,restrictedRarity:1,nav:3,route:4,primaryFaction:'Empire',factions:['Empire','Rebels','Local'],env:['jungle','crash','battlefield','passage'],jobs:['salvage','rebel','force'],services:['lodging','market','rebel']},
  ferrix:{id:'ferrix',name:'Rix Road',world:'Ferrix',region:'Free Trade Sector · Outer Rim',summary:'A tight-knit salvage town where hard-to-find components, salyards, covert communications, and Imperial scrutiny make every transaction political.',source:'Star Wars Encyclopedia · Ferrix',security:4,rarityMod:1,priceMod:.95,restrictedPrice:1.18,restrictedRarity:1,nav:3,route:5,primaryFaction:'Local',factions:['Local','Rebels','Empire','Guild'],env:['junkyard','chase','hangar','battlefield'],jobs:['salvage','rebel','smuggling'],services:['lodging','clinic','shipyard','cantina','market','blackmarket','fixer']},
  talus:{id:'talus',name:'Dearic',world:'Talus',region:'Corellian System · Core Region',summary:'Talus’s capital and primary spaceport presents polished commercial districts above a harsher network of corrupt, neglected neighborhoods.',source:'Suns of Fortune · Talus / Dearic',security:3,rarityMod:1,priceMod:1.00,restrictedPrice:1.10,restrictedRarity:1,nav:4,route:6,primaryFaction:'Local',factions:['Local','Empire','Guild'],env:['chase','cantina','hangar','junkyard'],jobs:['heist','smuggling','bounty'],services:['lodging','clinic','shipyard','cantina','market','blackmarket']},
  centerpoint:{id:'centerpoint',name:'Centerpoint Station',world:'Corellian System',region:'Core Region',summary:'An immense ancient station divided among tourism, shells of habitation, advanced research, and a less-policed southern criminal sector.',source:'Suns of Fortune · Centerpoint Station',security:3,rarityMod:0,priceMod:1.02,restrictedPrice:1.12,restrictedRarity:1,nav:4,route:6,primaryFaction:'Local',factions:['Local','Guild','Empire'],env:['lab','hangar','chase','cantina'],jobs:['heist','salvage','smuggling'],services:['lodging','clinic','shipyard','cantina','market','blackmarket','fixer']},
  dantooine:{id:'dantooine',name:'Colonial Landing',world:'Dantooine',region:'Outer Rim',summary:'A sparse agricultural frontier of grasslands, rivers, caves, farmers, nomadic Dantari, abandoned Rebel traces, and older Jedi history.',source:'Complete Species Guide v6 fan supplement · Dantooine / project reference',security:1,rarityMod:3,priceMod:1.08,restrictedPrice:1.02,restrictedRarity:0,nav:3,route:4,primaryFaction:'Local',factions:['Local','Rebels'],env:['grassland','jungle','crash','battlefield'],jobs:['salvage','rebel','force'],services:['lodging','clinic','market','rebel']}
});
Object.assign(SHIP_DESTINATIONS,Object.fromEntries(Object.entries(GALAXY_HUBS_50).map(([id,h])=>[id,{name:`${h.name} — ${h.world}`,diff:h.nav,desc:`${h.region}. ${h.summary}`}])));

Object.assign(DISTRICTS_51,{
  nalHutta:[
    {id:'bilbousaPort',name:'Bilbousa Port District',kind:'spaceport',skill:'Streetwise',diff:3,desc:'Offworld cargo and visitors are funneled through monitored docks before being allowed deeper into Hutt territory.',source:'Lords of Nal Hutta · Nal Hutta / Sable Reach adaptation',services:['shipyard','market'],npcs:[['Ruvo Drenn','Landing Broker','Hutts','Streetwise'],['Nella Vos','Cargo Assessor','Guild','Negotiation']]},
    {id:'councilQuarter',name:'Council Quarter',kind:'secure',skill:'Cool',diff:4,desc:'Administrative halls and audience compounds serve the endless negotiations surrounding the Hutt Ruling Council.',source:'Lords of Nal Hutta · Hutt Ruling Council / Sable Reach adaptation',services:['fixer'],npcs:[['Porga Kesh','Kajidic Clerk','Hutts','Knowledge (Underworld)'],['Tal Varo','Petition Runner','Local','Charm']]},
    {id:'palaceCanals',name:'Palace Canals',kind:'office',skill:'Perception',diff:3,desc:'Private estates and service routes rise from the swamps, guarded by retainers who notice unfamiliar traffic.',source:'Lords of Nal Hutta · Hutt palaces / Sable Reach adaptation',services:['blackmarket'],npcs:[['Dessa Noll','Estate Factor','Hutts','Negotiation']]},
    {id:'outerBog',name:'Outer Bog Routes',kind:'wilderness',skill:'Survival',diff:3,desc:'Misty channels and raised causeways skirt kajidic holdings where getting lost is safer than being noticed by the wrong household.',source:'Lords of Nal Hutta · Nal Hutta swamps / Sable Reach adaptation',services:[],npcs:[['Korr Daal','Swamp Guide','Local','Survival']]}
  ],
  toydaria:[
    {id:'merchant',name:'Toydor Merchant District',kind:'market',skill:'Negotiation',diff:2,desc:'Merchants, factors, and Hutt-connected buyers compete in the commercial heart of the capital.',source:'Lords of Nal Hutta · Toydor Merchant District',services:['market','cantina'],npcs:[['Vikko Tan','Merchant Vetting Agent','Local','Negotiation'],['Soola Grek','Hutt Factor','Hutts','Streetwise']]},
    {id:'royal',name:'Royal Palace Approach',kind:'secure',skill:'Charm',diff:3,desc:'Ceremonial approaches to the monarchy are orderly, crowded with petitioners, and watched by officials who know the value of protocol.',source:'Lords of Nal Hutta · Royal Palace / Sable Reach adaptation',services:[],npcs:[['Rinn Polla','Royal Functionary','Local','Charm']]},
    {id:'church',name:'Church of Toydaria Quarter',kind:'tourist',skill:'Knowledge (Lore)',diff:2,desc:'Pilgrims, families, and merchants pass through a quieter district shaped by Toydarian custom rather than offworld commerce.',source:'Lords of Nal Hutta · Church of Toydaria / Sable Reach adaptation',services:['lodging'],npcs:[['Ollo Fen','Local Archivist','Local','Knowledge (Lore)']]},
    {id:'oktos',name:'Oktos Marsh Line',kind:'imperial',skill:'Stealth',diff:3,desc:'Imperial sensors and customs patrols watch the southern marshes where legitimate traffic overlaps with dangerous spice routes.',source:'Lords of Nal Hutta · Oktos Zone Imperial Outpost / Sable Reach adaptation',services:[],npcs:[['Sergeant Darr Kelm','Customs Patrol NCO','Empire','Vigilance']]}
  ],
  empressTeta:[
    {id:'coreDistrict',name:'Cinnagar Core District',kind:'tourist',skill:'Cool',diff:3,desc:'High-end boutiques, museums, offices, and aristocratic traffic make the Core District prosperous and intensely status-conscious.',source:'Nexus of Power · Cinnagar Core District',services:['market','lodging'],npcs:[['Mira Keto','Society Concierge','Local','Charm'],['Venn Arcos','Customs Liaison','Empire','Cool']]},
    {id:'greatLibrary',name:'Great Library of Cinnagar',kind:'office',skill:'Knowledge (Lore)',diff:3,desc:'A vast public archive and museum preserves official Tetan history alongside artifacts and scholarly disputes.',source:'Nexus of Power · Great Library of Cinnagar',services:[],npcs:[['Dr. Senn Val','Archive Curator','Local','Knowledge (Lore)']]},
    {id:'guildhouse',name:"Navigator's Guildhouse",kind:'office',skill:'Astrogation',diff:3,desc:'Once a major center of route exploration, the guildhouse now operates beneath Imperial route restrictions and sells access carefully.',source:"Nexus of Power · Hyperspace Navigator's Guildhouse",services:['fixer'],npcs:[['Calo Rinn','Route Archivist','Guild','Astrogation']]},
    {id:'carbonite',name:'Carbonite Works',kind:'industrial',skill:'Mechanics',diff:3,desc:'Refining yards and logistics spines feed the system’s resource economy under Mining Guild supervision.',source:'Nexus of Power · Empress Teta carbonite economy / Sable Reach adaptation',services:['shipyard'],npcs:[['Jexa Mor','Shift Engineer','Guild','Mechanics']]}
  ],
  yavin4:[
    {id:'temple',name:'Great Temple Interior',kind:'rebel',skill:'Perception',diff:3,desc:'Recently evacuated command spaces still contain signs of hurried withdrawal, sealed rooms, and discarded logistics infrastructure.',source:'Star Wars Encyclopedia · Yavin 4 Rebel base / Sable Reach adaptation',services:['rebel'],npcs:[['Tess Ralo','Independent Salvager','Local','Perception']]},
    {id:'hangars',name:'Abandoned Hangar Terrace',kind:'industrial',skill:'Mechanics',diff:3,desc:'Empty launch positions and damaged servicing gear overlook the jungle where useful parts may have been left behind.',source:'Star Wars Encyclopedia · Yavin 4 base / Sable Reach adaptation',services:[],npcs:[['R3-K8','Salvage Survey Droid','Local','Mechanics']]},
    {id:'jungle',name:'Massassi Jungle Approach',kind:'wilderness',skill:'Survival',diff:3,desc:'Dense jungle obscures ancient structures, abandoned sensor positions, and anyone approaching the former base on foot.',source:'Star Wars Encyclopedia · Yavin 4 / Sable Reach adaptation',services:[],npcs:[['Pera Dane','Jungle Scout','Local','Survival']]},
    {id:'power',name:'Remote Power Station',kind:'outskirts',skill:'Computers',diff:4,desc:'A distant support site once fed defensive systems. Some circuits still answer, and that makes the ruin valuable to more than scavengers.',source:'Star Wars Encyclopedia · Yavin 4 hidden power station / Sable Reach adaptation',services:[],npcs:[['Kell Anor','Signal Hunter','Rebels','Computers']]}
  ],
  ferrix:[
    {id:'rixRoad',name:'Rix Road',kind:'market',skill:'Streetwise',diff:2,desc:'Workers, traders, salyard crews, and community institutions share the town’s central artery beneath the sound of the timekeeping gong.',source:'Star Wars Encyclopedia · Ferrix / Rix Road',services:['market','cantina'],npcs:[['Nela Brasso','Parts Runner','Local','Streetwise'],['Timm Vale','Inventory Broker','Guild','Negotiation']]},
    {id:'salyards',name:'Salyard Quarter',kind:'junkyard',skill:'Mechanics',diff:2,desc:'Refurbished machinery, stripped ship components, and unlicensed salvage change hands among technicians who know exactly what old hardware is worth.',source:'Star Wars Encyclopedia · Ferrix salyards / Sable Reach adaptation',services:['shipyard','blackmarket'],npcs:[['Sera Paak','Salyard Mechanic','Local','Mechanics']]},
    {id:'hotelHQ',name:'Occupied Hotel Block',kind:'imperial',skill:'Stealth',diff:4,desc:'A former hotel has become an Imperial operations point, extending surveillance into surrounding streets.',source:'Star Wars Encyclopedia · Imperial headquarters on Rix Road / Sable Reach adaptation',services:[],npcs:[['Lt. Merek Sol','Imperial Watch Officer','Empire','Vigilance']]},
    {id:'freight',name:'Freight & Grappler Yard',kind:'spaceport',skill:'Athletics',diff:2,desc:'Heavy salvage, freight tractors, and grappler crews keep the town supplied and provide discreet ways to move cargo.',source:'Star Wars Encyclopedia · Ferrix salvage culture / Sable Reach adaptation',services:['shipyard'],npcs:[['Boro Kelm','Grappler Foreman','Local','Athletics']]}
  ],
  talus:[
    {id:'spaceport',name:'Dearic Spaceport',kind:'spaceport',skill:'Streetwise',diff:2,desc:'Talus’s main spaceport feeds a city where legitimate commerce and quiet corruption operate side by side.',source:'Suns of Fortune · Dearic',services:['shipyard','market'],npcs:[['Dena Sol','Port Broker','Local','Streetwise']]},
    {id:'commercial',name:'Dearic Commercial Heights',kind:'market',skill:'Negotiation',diff:2,desc:'Broad parks and glittering towers frame prosperous shops whose polished presentation conceals fierce local politics.',source:'Suns of Fortune · Dearic / Sable Reach adaptation',services:['market','lodging'],npcs:[['Varo Pell','Commercial Agent','Local','Negotiation']]},
    {id:'swoop',name:'Swoop & Gaming Strip',kind:'casino',skill:'Cool',diff:3,desc:'The Double Worlds’ appetite for dangerous racing and gambling turns this strip into a magnet for risk-takers and fixers.',source:'Suns of Fortune · Talus/Tralus culture / Sable Reach adaptation',services:['cantina','blackmarket'],npcs:[['Kara Nox','Race Fixer','Guild','Cool']]},
    {id:'wards',name:'Hidden Wards',kind:'underlevels',skill:'Streetwise',diff:3,desc:'Neglected neighborhoods exist beyond the polished official image, with little protection except what locals can arrange themselves.',source:'Suns of Fortune · Dearic disadvantaged sectors / Sable Reach adaptation',services:['fixer'],npcs:[['Oren Vey','Neighborhood Organizer','Local','Streetwise']]}
  ],
  centerpoint:[
    {id:'hollowtown',name:'Hollowtown',kind:'tourist',skill:'Cool',diff:2,desc:'Tourism fills the great central hollow with visitors adjusting to an ancient station whose scale overwhelms first-time arrivals.',source:'Suns of Fortune · Centerpoint Hollowpoint/Hollowtown',services:['lodging','cantina','market'],npcs:[['Pell Saro','Tour Liaison','Local','Charm']]},
    {id:'shells',name:'The Shells',kind:'market',skill:'Streetwise',diff:2,desc:'Layers of habitation and commerce wrap the station in neighborhoods whose local rules change from deck to deck.',source:'Suns of Fortune · Centerpoint The Shells / Sable Reach adaptation',services:['market','clinic'],npcs:[['Ressa Quill','Deck Broker','Local','Streetwise']]},
    {id:'techsec',name:'TechSec',kind:'industrial',skill:'Computers',diff:3,desc:'Research labs and manufacturing projects dominate the northern technology sector.',source:'Suns of Fortune · Centerpoint TechSec',services:['shipyard'],npcs:[['Dr. Jor Venn','Systems Researcher','Guild','Computers']]},
    {id:'southPole',name:'South Pole Levels',kind:'blackmarket',skill:'Streetwise',diff:3,desc:'The least-explored polar region supports a small criminal ecosystem beyond the station’s polished tourist face.',source:'Suns of Fortune · Centerpoint South Pole / Sable Reach adaptation',services:['blackmarket','fixer'],npcs:[['Nix Tal','Station Fence','Guild','Streetwise']]}
  ],
  dantooine:[
    {id:'landing',name:'Colonial Landing',kind:'spaceport',skill:'Negotiation',diff:2,desc:'A modest landing field serves scattered farmers, traders, and outsiders moving supplies through a sparsely populated world.',source:'Complete Species Guide v6 fan supplement · Dantooine / Sable Reach adaptation',services:['market','lodging'],npcs:[['Mira Dant','Colonial Quartermaster','Local','Negotiation']]},
    {id:'oldBase',name:'Abandoned Rebel Site',kind:'rebel',skill:'Perception',diff:3,desc:'Old fortifications and hidden storage areas remain after the Alliance moved on, attracting scavengers and intelligence hunters.',source:'Complete Species Guide v6 fan supplement · recent Rebel base / Sable Reach adaptation',services:['rebel'],npcs:[['Kess Ordo','Former Rebel Scout','Rebels','Perception']]},
    {id:'grasslands',name:'Dantooine Grasslands',kind:'wilderness',skill:'Survival',diff:2,desc:'Open savannas, rivers, and isolated farms stretch between the few settled areas.',source:'Complete Species Guide v6 fan supplement · Dantooine terrain',services:[],npcs:[['Tanna Brell','Frontier Farmer','Local','Survival']]},
    {id:'caves',name:'River-Cut Caves',kind:'wilderness',skill:'Survival',diff:3,desc:'Natural caves in the hills preserve traces of wildlife, old travelers, and stories connected to the planet’s deeper history.',source:'Complete Species Guide v6 fan supplement · Dantooine / Sable Reach adaptation',services:[],npcs:[['Raal Garoo','Dantari Wayfinder','Local','Survival']]}
  ]
});

if(!SPECIES.dantari)SPECIES.dantari={name:'Dantari',xp:110,wt:11,st:11,c:{Brawn:3,Agility:2,Intellect:1,Cunning:2,Willpower:2,Presence:2},free:{Survival:1},note:'Begins with Survival 1. Primitive: checks involving unfamiliar advanced technology are harder; the full familiarity/removal edge case remains contextual.',source:'Complete Species Guide v6 fan supplement · Dantari'};
if(!SPECIES.sluissi)SPECIES.sluissi={name:'Sluissi',xp:90,wt:10,st:10,c:{Brawn:2,Agility:2,Intellect:3,Cunning:1,Willpower:2,Presence:2},free:{Discipline:1,Mechanics:1},note:'Begins with Discipline 1 and Mechanics 1. The source also grants Solid Repairs; this racial talent remains recorded rather than separately automated.',source:'Complete Species Guide v6 fan supplement · Sluissi'};
function refreshSpeciesSelect64(){let el=$('species');if(!el)return;let current=S.species;el.innerHTML=Object.entries(SPECIES).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');if(SPECIES[current])el.value=current}
refreshSpeciesSelect64();

if(!ADVERSARY_DB.some(x=>x.name==='Tetan Guard'))ADVERSARY_DB.push(
 {name:'Tetan Guard',type:'Rival',source:'Nexus of Power',summary:'Reference profile: Brawl 3, Coercion 2, Cool 3, Discipline 3, Ranged (Light) 2, Ranged (Heavy) 2, Vigilance 3; Body Guard 2; ceremonial blaster rifle Damage 9, Crit 3, Long, Stun; ceremonial armor +2 soak, +1 defense.'},
 {name:'Mining Guild Enforcer',type:'Rival',source:'Nexus of Power',summary:'Reference profile: Brawl 2, Coercion 2, Discipline 1, Streetwise 2, Vigilance 1; Loom; spiked knuckle-gloves Damage 5, Crit 3, Vicious 1; leather jacket +1 soak.'},
 {name:'Toydarian Swamptrooper Patrol',type:'Minion reference',source:'Lords of Nal Hutta',summary:'Reference profile from Toydaria material: group skills include Athletics, Discipline, Melee, Perception, Ranged (Heavy), Ranged (Light), Survival, Vigilance; blaster carbine, grenades, rebreather, swamp-adapted armor.'},
 {name:'Shaoryn',type:'Rival reference',source:'Lords of Nal Hutta',summary:'Reference creature: Brawl 2, Deception 4, Discipline 2, Stealth 3; Adversary 1; Force Rating 2; a deceptive Force-sensitive swamp predator associated with Toydaria.'}
);
if(!STARSHIP_DB.some(x=>x.name==='StarViper-class Attack Platform'))STARSHIP_DB.push({name:'StarViper-class Attack Platform',class:'Starfighter',manufacturer:'Mandal Hypernautics / MandalMotors',hyperdrive:'Class 2',sensor:'Close',price:160000,rarity:7,hp:0,source:'Starships and Speeders',implementation:'Reference record',weapons:'Arm-mounted heavy laser cannons: Damage 6, Crit 3, Short, Linked 1. Proton torpedo launchers: Damage 8, Crit 2, Short, Blast 6, Breach 6, Guided 2, Limited Ammo 6, Linked 1, Slow-Firing 1. One pilot; Encumbrance 12; no passengers; one week consumables.'});

const FACTIONS_64=['Empire','Rebels','Hutts','Guild','Local'];
const INFLUENCE_SEED_64={
 sable:{Empire:12,Rebels:15,Hutts:10,Guild:35,Local:65},tatooine:{Empire:20,Rebels:5,Hutts:62,Guild:42,Local:35},saleucami:{Empire:18,Rebels:8,Hutts:10,Guild:55,Local:52},ordMantell:{Empire:30,Rebels:8,Hutts:38,Guild:52,Local:45},narShaddaa:{Empire:12,Rebels:5,Hutts:78,Guild:55,Local:32},bespin:{Empire:38,Rebels:8,Hutts:10,Guild:25,Local:58},lothal:{Empire:78,Rebels:42,Hutts:5,Guild:15,Local:45},corellia:{Empire:72,Rebels:28,Hutts:5,Guild:25,Local:52},
 nalHutta:{Empire:25,Rebels:3,Hutts:92,Guild:45,Local:20},toydaria:{Empire:48,Rebels:10,Hutts:55,Guild:32,Local:62},empressTeta:{Empire:82,Rebels:8,Hutts:5,Guild:60,Local:45},yavin4:{Empire:48,Rebels:46,Hutts:3,Guild:5,Local:12},ferrix:{Empire:58,Rebels:50,Hutts:5,Guild:20,Local:72},talus:{Empire:48,Rebels:12,Hutts:10,Guild:38,Local:60},centerpoint:{Empire:35,Rebels:15,Hutts:10,Guild:48,Local:65},dantooine:{Empire:22,Rebels:38,Hutts:5,Guild:12,Local:70}
};
const DYNAMIC_EVENTS_64={
 crackdown:{name:'Security Crackdown',detail:'Imperial security increases patrols and transaction checks.',apply:(hub,I,p)=>{I.Empire+=7;I.Local-=2;p.rarityDelta=1;p.securityDelta=1;p.until=S.world.day+2;S.world.sectorHeat[hub]=Math.min(10,(S.world.sectorHeat[hub]||0)+1)}},
 rebelAction:{name:'Rebel Action',detail:'A local Rebel operation exposes Imperial weakness but raises tension.',apply:(hub,I,p)=>{I.Rebels+=7;I.Empire-=3;I.Local+=1;p.securityDelta=1;p.until=S.world.day+1}},
 huttDeal:{name:'Kajidic Deal',detail:'Hutt money and favors reshape illicit trade routes.',apply:(hub,I,p)=>{I.Hutts+=6;I.Guild+=2;I.Local-=2;p.priceDelta=-.04;p.restrictedDelta=-1;p.until=S.world.day+2}},
 guildRush:{name:'Contract Rush',detail:'Hunters, brokers, and independent operators flood the local contract market.',apply:(hub,I,p)=>{I.Guild+=6;I.Local+=1;p.priceDelta=.02;p.until=S.world.day+1}},
 localPushback:{name:'Local Pushback',detail:'Residents and local institutions resist outside control.',apply:(hub,I,p)=>{let ext=['Empire','Hutts','Guild','Rebels'].sort((a,b)=>I[b]-I[a])[0];I.Local+=7;I[ext]-=3;p.securityDelta=-1;p.until=S.world.day+1}},
 marketBoom:{name:'Market Boom',detail:'A temporary surplus improves legal availability and prices.',apply:(hub,I,p)=>{I.Local+=2;I.Guild+=2;p.priceDelta=-.06;p.rarityDelta=-1;p.until=S.world.day+2}},
 securityVacuum:{name:'Security Vacuum',detail:'Local enforcement fractures, making trade easier but the streets less predictable.',apply:(hub,I,p)=>{I.Local-=2;I.Guild+=2;I.Hutts+=2;p.securityDelta=-1;p.restrictedDelta=-1;p.until=S.world.day+2}}
};

const _p64Ensure62Base=ensurePhase62State;
function ensurePhase64State(){
  _p64Ensure62Base();S.schemaVersion=64;let W=S.world||(S.world={});
  W.sim64=W.sim64&&typeof W.sim64==='object'?W.sim64:{};let G=W.sim64;
  G.influence=G.influence&&typeof G.influence==='object'?G.influence:{};G.events=Array.isArray(G.events)?G.events:[];G.lastControl=G.lastControl&&typeof G.lastControl==='object'?G.lastControl:{};G.marketPulse=G.marketPulse&&typeof G.marketPulse==='object'?G.marketPulse:{};
  for(const hid of Object.keys(GALAXY_HUBS_50)){
    let seed=INFLUENCE_SEED_64[hid]||{Empire:20,Rebels:15,Hutts:15,Guild:25,Local:55};G.influence[hid]=G.influence[hid]&&typeof G.influence[hid]==='object'?G.influence[hid]:{};
    for(const f of FACTIONS_64)if(!Number.isFinite(G.influence[hid][f]))G.influence[hid][f]=Number(seed[f]||0);
    if(!G.lastControl[hid])G.lastControl[hid]=control64Raw(G.influence[hid]);
    if(!G.marketPulse[hid]||typeof G.marketPulse[hid]!=='object')G.marketPulse[hid]={priceDelta:0,rarityDelta:0,restrictedDelta:0,securityDelta:0,until:0};
  }
  if(!Number.isFinite(G.lastPulseDay))G.lastPulseDay=Number(W.day||1);
  for(const hid of Object.keys(G.marketPulse)){let p=G.marketPulse[hid];if((p.until||0)<W.day){p.priceDelta=0;p.rarityDelta=0;p.restrictedDelta=0;p.securityDelta=0}}
  return G;
}
function control64Raw(I){return FACTIONS_64.slice().sort((a,b)=>(I?.[b]||0)-(I?.[a]||0))[0]||'Local'}
function influence64(hubId=null){let G=ensurePhase64State();return G.influence[hubId||S.world.currentHub]}
function control64(hubId=null){return control64Raw(influence64(hubId))}
function controlMargin64(hubId=null){let v=Object.values(influence64(hubId)).sort((a,b)=>b-a);return (v[0]||0)-(v[1]||0)}
function stability64(hubId=null){let m=controlMargin64(hubId);return m<8?'CONTESTED':m<20?'UNSTABLE':'DOMINANT'}
function marketPulse64(hubId=null){let G=ensurePhase64State(),id=hubId||S.world.currentHub,p=G.marketPulse[id];return (p&&p.until>=S.world.day)?p:{priceDelta:0,rarityDelta:0,restrictedDelta:0,securityDelta:0,until:0}}
function effectiveSecurity64(hubId=null){let id=hubId||S.world.currentHub,h=GALAXY_HUBS_50[id]||hub50(id),p=marketPulse64(id),ctl=control64(id);let bonus=ctl==='Empire'?1:ctl==='Hutts'&&h.region.includes('Hutt Space')?1:0;return Math.max(0,Math.min(5,h.security+bonus+(p.securityDelta||0)))}
function clampInfluence64(I){for(const f of FACTIONS_64)I[f]=Math.max(0,Math.min(100,Math.round(Number(I[f]||0))))}
function hash64(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function galaxyEventForDay64(day,hubId,salt=0){let keys=Object.keys(DYNAMIC_EVENTS_64),n=hash64(`${day}:${hubId}:${salt}`);return keys[n%keys.length]}
function choosePulseHubs64(day){let ids=Object.keys(GALAXY_HUBS_50),a=ids[hash64(`${day}:a`)%ids.length],b=ids[hash64(`${day}:b`)%ids.length];return a===b?[a]:[a,b]}
function recordPulse64(day,hub,event,oldCtl,newCtl){let G=S.world.sim64,e={day,hub,event,oldCtl,newCtl,text:DYNAMIC_EVENTS_64[event].detail};G.events.unshift(e);G.events=G.events.slice(0,48);if(oldCtl!==newCtl){G.lastControl[hub]=newCtl;addWorldConsequence50(`${GALAXY_HUBS_50[hub].name}: ${newCtl} overtakes ${oldCtl} as the strongest local influence.`,'faction');if(hub===S.world.currentHub)S.world.localOffers=[]}}
function simulateOneDay64(day){let G=ensurePhase64State();for(const [idx,hid] of choosePulseHubs64(day).entries()){let ev=galaxyEventForDay64(day,hid,idx),I=G.influence[hid],p=G.marketPulse[hid],old=control64Raw(I);DYNAMIC_EVENTS_64[ev].apply(hid,I,p);clampInfluence64(I);let now=control64Raw(I);recordPulse64(day,hid,ev,old,now)}G.lastPulseDay=day}
function simulateToDay64(){let G=ensurePhase64State(),target=Math.max(1,Number(S.world.day||1));while(G.lastPulseDay<target)simulateOneDay64(G.lastPulseDay+1);return G}
function adjustInfluence64(hubId,faction,amount,reason=''){let G=ensurePhase64State(),I=G.influence[hubId];if(!I||!FACTIONS_64.includes(faction))return;let old=control64Raw(I);I[faction]+=amount;clampInfluence64(I);let now=control64Raw(I);if(reason)G.events.unshift({day:S.world.day,hub:hubId,event:'player',oldCtl:old,newCtl:now,text:reason});G.events=G.events.slice(0,48);if(old!==now){G.lastControl[hubId]=now;addWorldConsequence50(`${GALAXY_HUBS_50[hubId].name}: the crew's actions help ${now} become the strongest local influence.`,'faction');if(hubId===S.world.currentHub)S.world.localOffers=[]}}
function districtController64(d=currentDistrict52(),hubId=null){let hid=hubId||S.world.currentHub,I=influence64(hid);if(d.kind==='imperial')return'Empire';if(d.kind==='rebel')return'Rebels';if(['blackmarket','underlevels','undercity','casino'].includes(d.kind))return['Hutts','Guild','Local'].sort((a,b)=>I[b]-I[a])[0];if(d.kind==='secure')return['Empire','Local','Hutts'].sort((a,b)=>I[b]-I[a])[0];if(['wilderness','outskirts'].includes(d.kind))return['Local','Rebels'].sort((a,b)=>I[b]-I[a])[0];return control64Raw(I)}

const _p64BaseHubPriceMod=hubPriceMod50;
hubPriceMod50=function(item){ensurePhase64State();let m=_p64BaseHubPriceMod(item),ctl=control64(),p=marketPulse64();if(item?.restricted){if(ctl==='Empire')m*=1.12;if(ctl==='Hutts'||ctl==='Guild')m*=.92;if(ctl==='Rebels')m*=.97}else{if(ctl==='Local')m*=.97;if(ctl==='Empire')m*=1.02}m*=1+(p.priceDelta||0);return Math.max(.65,Math.min(1.75,m))};
function restrictedControlDelta64(hubId=null){let c=control64(hubId);return c==='Empire'?1:(c==='Hutts'||c==='Guild'?-1:0)}
previewMarketTerms50=function(item){let h=hub50(),p=marketPulse64(),rarity=Math.max(0,(item?.rarity||0)+(item?.restricted?(h.restrictedRarity||0)+restrictedControlDelta64()+Number(p.restrictedDelta||0):0)),price=Math.max(1,Math.round((item?.price||0)*hubPriceMod50(item))),effective=Math.max(0,rarity+h.rarityMod+Math.floor(localHeat50()/5)+Number(p.rarityDelta||0)),diff=effective<=1?0:effective<=3?1:effective<=5?2:effective<=7?3:effective<=9?4:5,upgrade=Math.max(0,effective-10);return{rarity,price,effective,diff,upgrade,modifier:effective-(item?.rarity||0)}};
marketRarityModifier=function(){let h=hub50(),p=marketPulse64();return h.rarityMod+Math.floor(localHeat50()/5)+Number(p.rarityDelta||0)};
blackMarketTerms=function(item){let h=hub50(),p=marketPulse64(),rarity=Math.max(0,(item.rarity||0)+(item.restricted?(h.restrictedRarity||0)+restrictedControlDelta64()+Number(p.restrictedDelta||0):0)),price=Math.max(1,Math.round((item.price||0)*hubPriceMod50(item))),used=0,max=talentRank('Black Market Contacts');if(item.restricted&&max>0&&confirm(`Use Black Market Contacts for ${item.name}? Reduce rarity by up to ${max}; each rank used raises the dynamically adjusted price by 50%.`)){used=Math.max(0,Math.min(max,Number(prompt('Black Market Contacts ranks to use',String(max)))||0));rarity=Math.max(0,rarity-used);price=Math.round(price*(1+0.5*used))}return{rarity,price,used}};

arrivalEvent50=function(dest){ensurePhase64State();let h=hub50(dest),sec=effectiveSecurity64(dest),pressure=S.world.imperialHeat+localHeat50(dest)+sec;if(pressure>=8&&sec>=3){S.world.pendingEvent={type:'checkpoint',hub:dest,title:`Inspection at ${h.name}`,text:`${control64(dest)} currently holds the strongest local influence, and security has your transponder flagged for secondary inspection.`,diff:Math.min(5,sec)};return}let rival=S.world.rivals.find(r=>r.status==='active'&&r.hub===dest&&r.threat>=2);if(rival)S.world.pendingEvent={type:'rival',hub:dest,rivalId:rival.id,title:`${rival.name} is waiting`,text:`${rival.grudge} The rival has tracked the crew to ${h.name}.`,diff:Math.min(5,1+rival.threat)}};
const CONTROL_JOB_BIAS_64={Empire:['bounty','rescue'],Rebels:['rebel','rescue','salvage'],Hutts:['smuggling','heist','bounty'],Guild:['bounty','salvage','smuggling'],Local:null};
localOperation50=function(){ensurePhase64State();let h=hub50(),ctl=control64(),pool=CONTROL_JOB_BIAS_64[ctl]||h.jobs,type=opPick(pool.filter(x=>OPERATION_TYPES[x])||h.jobs),env=opPick(h.env),sec=effectiveSecurity64(),threat=Math.max(1,Math.min(5,1+Math.floor(Math.random()*4)+Math.floor((localHeat50()+sec)/5))),op=buildOperation(type,threat,env);op.hub=S.world.currentHub;op.location=h.name;op.source=`${op.source} · Localized at ${h.name} · ${ctl}-influenced board`;op.dynamicController=ctl;let factionPool=(h.factions||[]).filter(f=>FACTIONS_64.includes(f));op.repFaction=factionPool.includes(ctl)?ctl:(opPick(factionPool)||h.primaryFaction);if(op.repFaction==='Empire'&&type==='rebel')op.repFaction='Rebels';let rep=factionRep50(h.primaryFaction);op.credits=Math.max(100,Math.round(op.credits*(1+(rep>=10?.08:rep<=-10?.15:0))));return op};

function renderGalaxyPulse64(){if(!$('galaxy'))return;ensurePhase64State();simulateToDay64();let h=hub50(),G=S.world.sim64,I=G.influence[h.id],ctl=control64(h.id),margin=controlMargin64(h.id),p=marketPulse64(h.id);let host=$('galaxyPulse64');if(!host){host=document.createElement('div');host.id='galaxyPulse64';host.className='galaxy-pulse64';let dest=$('galaxyDestinations50')?.closest('.card');(dest?.parentNode||$('galaxy')).insertBefore(host,dest?.nextSibling||null)}let bars=FACTIONS_64.map(f=>`<div class="influence-cell64 faction-${f}"><div class="row"><span class="tiny">${f}</span><b>${I[f]}</b></div><div class="influence-track64"><div class="influence-fill64" style="width:${I[f]}%"></div></div></div>`).join('');let controls=Object.keys(GALAXY_HUBS_50).map(id=>{let c=control64(id),m=controlMargin64(id);return`<div class="control-card64"><div class="row"><b>${opEsc(GALAXY_HUBS_50[id].name)}</b><span class="control-chip64 faction-${c}">${c}</span></div><div class="tiny">${stability64(id)} · lead ${m}</div></div>`}).join('');let events=G.events.slice(0,6).map(e=>`<div class="pulse-event64"><span class="tiny">Day ${e.day} · ${opEsc(GALAXY_HUBS_50[e.hub]?.name||e.hub)}</span><br><b>${e.event==='player'?'Crew Consequence':opEsc(DYNAMIC_EVENTS_64[e.event]?.name||e.event)}</b> · ${opEsc(e.text||'')}</div>`).join('')||'<div class="small">The first faction pulse will occur when the campaign advances to another day.</div>';host.innerHTML=`<div class="row"><div><b>Galaxy Pulse</b><div class="small">Phase 64 · persistent faction influence, local control, security, markets, and mission pressure.</div></div><span class="tag ${stability64(h.id)==='CONTESTED'?'bad':stability64(h.id)==='UNSTABLE'?'gold':'good'}">${stability64(h.id)}</span></div><div class="row" style="margin-top:10px"><div><b>${opEsc(h.name)}</b><div class="small"><span class="faction-${ctl}"><b>${ctl}</b></span> currently leads by ${margin}. Effective Security ${effectiveSecurity64(h.id)}/5.</div></div><div class="tiny">${p.until>=S.world.day?`Market shift through Day ${p.until}`:'No temporary market event'}</div></div><div class="influence-grid64">${bars}</div><details style="margin-top:10px"><summary><b>Faction control across ${Object.keys(GALAXY_HUBS_50).length} hubs</b></summary><div class="control-grid64">${controls}</div></details><details style="margin-top:10px"><summary><b>Recent galactic developments</b></summary><div style="margin-top:7px">${events}</div></details><div class="tiny" style="margin-top:9px">Influence scores and simulation modifiers are original Sable Reach systems. Source material provides the places, factions, and political context—not these numerical control values.</div>`;
  if($('galaxyCurrent50')&&!$('galaxyCurrent50').querySelector('.phase64-current')){$('galaxyCurrent50').insertAdjacentHTML('beforeend',`<div class="phase64-current district-control64"><span class="pill faction-${ctl}">Control: ${ctl}</span><span class="pill">Effective Security ${effectiveSecurity64(h.id)}/5</span></div>`)}
  document.querySelectorAll('[data-galaxytravel50]').forEach(b=>{let id=b.dataset.galaxytravel50,card=b.closest('.item');if(card&&!card.querySelector('.phase64-dest'))card.insertAdjacentHTML('beforeend',`<div class="phase64-dest tiny" style="margin-top:6px"><span class="faction-${control64(id)}"><b>${control64(id)}</b></span> influence · ${stability64(id)} · effective security ${effectiveSecurity64(id)}/5</div>`)});
}
function renderDistrictControl64(){if(!$('explore')||!S.finalized)return;ensurePhase64State();let d=currentDistrict52(),c=districtController64(d),I=influence64(),scene=$('districtScene52');if(scene){scene.querySelector('.phase64-district')?.remove();scene.insertAdjacentHTML('beforeend',`<div class="phase64-district district-control64"><span class="pill faction-${c}">Local influence: ${c}</span><span class="pill">Hub control: ${control64()}</span></div>`)}document.querySelectorAll('[data-district52]').forEach(b=>{let dd=districts52().find(x=>x.id===b.dataset.district52);if(!dd)return;let x=b.querySelector('.phase64-nodecontrol');if(!x){x=document.createElement('div');x.className='phase64-nodecontrol tiny';b.appendChild(x)}x.innerHTML=`<span class="faction-${districtController64(dd)}">${districtController64(dd)}</span>`})}

const _p64Serializable=serializableState;serializableState=function(){ensurePhase64State();let x=_p64Serializable();x.schemaVersion=64;S.schemaVersion=64;return x};
const _p64RenderGalaxy=renderGalaxy50;renderGalaxy50=function(){ensurePhase64State();simulateToDay64();let r=_p64RenderGalaxy();renderGalaxyPulse64();return r};
const _p64RenderExplore=renderExplore52;renderExplore52=function(){ensurePhase64State();let r=_p64RenderExplore();renderDistrictControl64();return r};
const _p64RenderAll=renderAll;renderAll=function(){ensurePhase64State();simulateToDay64();let r=_p64RenderAll();S.schemaVersion=64;renderGalaxyPulse64();renderDistrictControl64();return r};
const _p64Travel=travelGalaxy50;travelGalaxy50=function(dest){let beforeDay=Number(S.world?.day||1),r=_p64Travel(dest);ensurePhase64State();if(S.world.day>beforeDay)simulateToDay64();renderGalaxyPulse64();return r};
const _p64HubService=useHubService50;useHubService50=function(service){let before=Number(S.world?.day||1),r=_p64HubService(service);ensurePhase64State();if(S.world.day>before)simulateToDay64();renderGalaxyPulse64();return r};
const _p64CampaignRest=campaignRest;campaignRest=function(){let before=Number(S.world?.day||1),r=_p64CampaignRest();ensurePhase64State();if(Number(S.world.day||1)===before)S.world.day=before+1;simulateToDay64();renderAll();return r};
const _p64Claim=claimOperationReward;claimOperationReward=function(){let op=S.gmOps?.current?{...S.gmOps.current}:null,was=!!S.gmOps?.current?.rewarded,r=_p64Claim();if(op&&!was){let hub=op.hub&&GALAXY_HUBS_50[op.hub]?op.hub:S.world.currentHub,f=FACTIONS_64.includes(op.repFaction)?op.repFaction:(GALAXY_HUBS_50[hub]?.primaryFaction||'Local');adjustInfluence64(hub,f,4,`${op.title} strengthens ${f} influence.`);let rivals=FACTIONS_64.filter(x=>x!==f).sort((a,b)=>influence64(hub)[b]-influence64(hub)[a]);if(rivals[0])adjustInfluence64(hub,rivals[0],-2,`${op.title} costs ${rivals[0]} local leverage.`);renderGalaxyPulse64()}return r};

function injectPhase64Guide(){if($('guide')&&!$('phase64Guide')){let c=document.createElement('div');c.id='phase64Guide';c.className='card';c.style.marginTop='12px';c.innerHTML=`<div class="row"><div><b>Phases 63–64 · Expanded & Dynamic Galaxy</b><div class="small">16 travel hubs now feed exploration, markets, local missions, faction control, and persistent day-by-day changes.</div></div><span class="tag good">LIVE</span></div><div class="small" style="margin-top:8px">Travel, lodging, and full downtime days advance the Galaxy Pulse. Factions can gain or lose influence; the controlling faction affects security, restricted markets, and the kinds of jobs most likely to appear. The numerical simulation is an original Sable Reach layer rather than an FFG rule.</div>`;$('guide').appendChild(c)}}
const _p64RenderGuide=renderGuide;renderGuide=function(){let r=_p64RenderGuide();injectPhase64Guide();return r};

RULE_AUDIT.unshift(
 {id:'galacticExpansion63',name:'Phase 63 Galactic Expansion',status:'adapted',source:'Lords of Nal Hutta; Nexus of Power; Suns of Fortune; Star Wars Encyclopedia; Complete Species Guide v6 fan supplement',detail:'Adds eight source-grounded destinations—Nal Hutta, Toydaria, Empress Teta, Yavin 4, Ferrix, Talus, Centerpoint Station, and Dantooine—with 32 explorable districts. Named locations and cited species/reference profiles follow supplied project sources; generic NPCs, service placement, routes, and market values are Sable Reach adaptations.'},
 {id:'dynamicGalaxy64',name:'Phase 64 Dynamic Galaxy Simulation',status:'adapted',source:'Original Sable Reach simulation informed by faction conflicts and setting context in the supplied sourcebooks',detail:'Adds persistent Empire/Rebel/Hutt/Guild/Local influence, controller changes, contested hubs, day-based events, temporary market/security effects, control-biased job boards, district influence, and player-driven shifts. Influence numbers and simulation math are original videogame systems.'}
);

const _p64Diagnostics=phase45Diagnostics;phase45Diagnostics=function(){let rows=_p64Diagnostics().filter(x=>x.name!=='Save schema'&&x.name!=='Save serialization'&&!/Phase 62 save (schema|serialization)/.test(x.name));const add=(name,ok,detail='')=>rows.push({name,ok:!!ok,detail});ensurePhase64State();let hubs=Object.keys(GALAXY_HUBS_50),districtCount=Object.values(DISTRICTS_51).reduce((n,a)=>n+a.length,0);add('Phase 63 galactic hubs',hubs.length>=16,`${hubs.length} hubs`);add('Phase 63 district coverage',hubs.every(id=>Array.isArray(DISTRICTS_51[id])&&DISTRICTS_51[id].length>=4),`${districtCount} districts across all hubs`);add('Phase 63 species expansion',!!SPECIES.dantari&&!!SPECIES.sluissi,'Dantari + Sluissi source profiles');add('Phase 63 reference expansion',ADVERSARY_DB.some(x=>x.name==='Tetan Guard')&&ADVERSARY_DB.some(x=>x.name==='Shaoryn')&&STARSHIP_DB.some(x=>x.name==='StarViper-class Attack Platform'),'new adversary/ship references indexed');add('Phase 64 influence coverage',hubs.every(id=>FACTIONS_64.every(f=>Number.isFinite(S.world.sim64.influence[id]?.[f]))),`${hubs.length} hubs × ${FACTIONS_64.length} factions`);add('Phase 64 controllers',hubs.every(id=>FACTIONS_64.includes(control64(id))),'every hub resolves a controller');add('Phase 64 save schema',S.schemaVersion===64&&BUILD_INFO.saveSchema===64&&serializableState().schemaVersion===64,'schema 64');try{let x=JSON.parse(JSON.stringify(serializableState()));add('Phase 64 save serialization',x.schemaVersion===64&&typeof x.world?.sim64==='object','dynamic galaxy survives JSON round-trip')}catch(e){add('Phase 64 save serialization',false,e.message)}return rows};
const _p64Smoke=runSableReachSmoke;runSableReachSmoke=async function(){let report=await _p64Smoke();report.failed=report.failed.filter(x=>!x.startsWith('build metadata:')&&!/^Phase (62 schema target):/.test(x)&&!x.startsWith('Phase 49 exposes eight galactic hubs:')&&!x.startsWith('Phase 49 galaxy UI renders:'));const test=(name,fn)=>{try{if(fn()===false)throw new Error('returned false');report.passed.push(name)}catch(e){report.failed.push(`${name}: ${e.message}`)}};ensurePhase64State();injectPhase64Guide();let hubs=Object.keys(GALAXY_HUBS_50);test('Phase 63 expands galaxy to sixteen hubs',()=>hubs.length===16);test('Phase 63 gives every hub at least four districts',()=>hubs.every(id=>DISTRICTS_51[id]?.length>=4));test('Phase 63 adds Nal Hutta Toydaria Empress Teta and Centerpoint',()=>['nalHutta','toydaria','empressTeta','centerpoint'].every(id=>!!GALAXY_HUBS_50[id]));test('Phase 63 adds Yavin 4 Ferrix Talus and Dantooine',()=>['yavin4','ferrix','talus','dantooine'].every(id=>!!GALAXY_HUBS_50[id]));test('Phase 63 adds Dantari and Sluissi',()=>SPECIES.dantari?.c?.Brawn===3&&SPECIES.sluissi?.c?.Intellect===3);test('Phase 63 species are selectable in character creator',()=>[...document.querySelectorAll('#species option')].some(o=>o.value==='dantari')&&[...document.querySelectorAll('#species option')].some(o=>o.value==='sluissi'));test('Phase 63 indexes new reference profiles',()=>ADVERSARY_DB.some(x=>x.name==='Tetan Guard')&&STARSHIP_DB.some(x=>x.name==='StarViper-class Attack Platform'));test('Phase 64 initializes five-faction influence for all hubs',()=>hubs.every(id=>FACTIONS_64.every(f=>Number.isFinite(S.world.sim64.influence[id][f]))));test('Phase 64 event selection is deterministic',()=>galaxyEventForDay64(17,'ferrix',0)===galaxyEventForDay64(17,'ferrix',0));test('Phase 64 resolves a controller for every hub',()=>hubs.every(id=>FACTIONS_64.includes(control64(id))));test('Phase 64 Galaxy Pulse renders',()=>{renderGalaxy50();return !!$('galaxyPulse64')&&$('galaxyPulse64').textContent.includes('Galaxy Pulse')});test('Phase 64 schema target',()=>BUILD_INFO.saveSchema===64&&S.schemaVersion===64&&serializableState().schemaVersion===64);document.body.dataset.smokeStatus=report.failed.length?'FAIL':'PASS';document.body.dataset.smokePassed=String(report.passed.length);document.body.dataset.smokeFailed=String(report.failed.length);window.__SABLE_REACH_SMOKE__=report;let pre=$('smokeReport');if(pre)pre.textContent=JSON.stringify(report,null,2);return report};

save=function(){try{let current=localStorage.getItem(RC_SAVE_KEY);if(current)localStorage.setItem(RC_BACKUP_KEY,current);S.lastSaved=new Date().toISOString();localStorage.setItem(RC_SAVE_KEY,JSON.stringify(serializableState()));bLog('Saved Phase 64: expanded galaxy, exploration hubs, faction influence, dynamic markets, security, and persistent Galaxy Pulse. Previous manual save preserved as backup.');updateGlobalStatus();renderGuide()}catch(err){showRuntimeError(`Save failed: ${err.message}`)}};

ensurePhase64State();simulateToDay64();document.title='Star Wars: Sable Reach — Phase 64';renderAll();injectPhase64Guide();
window.__SABLE_REACH__={version:BUILD_INFO.version,diagnostics:()=>rcStateIssues(),smoke:runSableReachSmoke,state:()=>S,galaxy:()=>({hubs:GALAXY_HUBS_50,influence:S.world?.sim64?.influence})};
