
/* =========================
   PHASES 55–56 — LOCAL MAPS, INTERACTABLES & SCRIPTED CONSEQUENCES
   ========================= */
BUILD_INFO.version='56.0.0-local-maps-scripted-scenes';BUILD_INFO.saveSchema=56;

const _p56Ensure54=ensurePhase54State;
function ensurePhase56State(){
  _p56Ensure54();S.schemaVersion=56;S.world=S.world||{};S.world.explore56=S.world.explore56||{};let E=S.world.explore56;
  E.currentHotspot=E.currentHotspot||{};E.discovered=E.discovered||{};E.unlocked=E.unlocked||{};E.looted=E.looted||{};E.terminals=E.terminals||{};E.environment=E.environment||{};E.scripted=E.scripted||{};E.dialogueChoices=E.dialogueChoices||{};E.npcStatus=E.npcStatus||{};E.mapNotice=E.mapNotice||'';E.pendingCombat=E.pendingCombat||null;
  let sk=sceneKey55();if(!E.currentHotspot[sk])E.currentHotspot[sk]='entry';syncNpcMoves56();
}
const _p56Ensure52=ensurePhase52State;ensurePhase52State=function(){_p56Ensure52();S.schemaVersion=56};
const _p56Ensure43=ensurePhase43State;ensurePhase43State=function(){_p56Ensure43();S.schemaVersion=56};
const _p56Ensure45=ensurePhase45State;ensurePhase45State=function(){_p56Ensure45();S.schemaVersion=56};
const _p56Ensure46=ensurePhase46State;ensurePhase46State=function(){_p56Ensure46();S.schemaVersion=56};
const _p56Ensure48=ensurePhase48State;ensurePhase48State=function(){_p56Ensure48();S.schemaVersion=56};
const _p56Ensure50=ensurePhase50State;ensurePhase50State=function(){_p56Ensure50();S.schemaVersion=56};
const _p56Ensure54Public=ensurePhase54State;ensurePhase54State=function(){_p56Ensure54Public();S.schemaVersion=56};
const _p56Serializable=serializableState;serializableState=function(){let x=_p56Serializable();x.schemaVersion=56;S.schemaVersion=56;return x};

function sceneKey55(){return `${districtKey53()}:${currentScene53().id}`}
function routeKey55(){return `${districtKey53()}:route:s1-s2`}
function routeRequiresUnlock55(){return ['secure','imperial','office','blackmarket','industrial'].includes(currentDistrict52().kind)}
function routeUnlocked55(){return !routeRequiresUnlock55()||!!S.world.explore56.unlocked[routeKey55()]}
function hotspotSkill55(type){let d=currentDistrict52(),sc=currentScene53();if(type==='terminal')return'Computers';if(type==='container')return['junkyard','industrial'].includes(d.kind)?'Mechanics':'Skulduggery';if(type==='door')return['office','secure'].includes(d.kind)?'Computers':'Skulduggery';if(type==='hidden')return d.kind==='wilderness'?'Survival':'Perception';if(type==='environment')return sc.skill;return d.skill}
function hotspotDiff55(type){let sc=currentScene53(),d=currentDistrict52();if(type==='door')return Math.max(2,sc.diff+(routeRequiresUnlock55()?1:0));if(type==='hidden')return Math.max(2,d.diff);if(type==='terminal')return Math.max(1,sc.diff);return Math.max(1,sc.diff)}
function currentActiveQuest56(){ensurePhase54State();return S.world.explore54.quests.find(q=>q.status==='active'&&q.hub===S.world.currentHub&&q.target===currentDistrict52().id)||null}
function mapNodes55(){
  ensurePhase56State();let E=S.world.explore56,sk=sceneKey55(),sc=currentScene53(),q=currentActiveQuest56(),hidden=!!E.discovered[sk];
  let terminalName=['office','secure','imperial'].includes(currentDistrict52().kind)?'Security Terminal':'Local Terminal';
  let containerName=['junkyard','industrial','spaceport'].includes(currentDistrict52().kind)?'Cargo Cache':'Storage Locker';
  let doorName=routeRequiresUnlock55()&&sc.id==='s1'&&!routeUnlocked55()?'Locked Route':'Secured Door';
  let a=[
    {id:'entry',name:'Entry Point',type:'entry',icon:'◎',x:1,y:2,desc:`The crew's current way into ${sc.name}.`},
    {id:'terminal',name:terminalName,type:'terminal',icon:'▣',x:2,y:1,done:!!E.terminals[sk],desc:'A terminal can reveal schedules, records, cameras, or local system access.'},
    {id:'environment',name:'Scene Feature',type:'environment',icon:'◇',x:2,y:2,done:!!E.environment[sk],desc:'A useful environmental feature can be studied or manipulated before trouble starts.'},
    {id:'container',name:containerName,type:'container',icon:'▤',x:2,y:3,done:!!E.looted[`${sk}:container`],desc:'An unattended container may hold salvage, supplies, or somebody else’s property.'},
    {id:'door',name:doorName,type:'door',icon:routeUnlocked55()?'▱':'▰',x:3,y:2,locked:routeRequiresUnlock55()&&sc.id==='s1'&&!routeUnlocked55(),done:!!E.unlocked[`${sk}:door`],desc:'A controlled access point leads away from the public path.'}
  ];
  if(hidden)a.push({id:'hidden',name:'Hidden Room',type:'hidden',icon:'✦',x:3,y:1,hidden:true,done:!!E.looted[`${sk}:hidden`],desc:'A concealed maintenance room or forgotten alcove that was not visible on first inspection.'});
  if(q&&q.step>=1)a.push({id:'quest',name:'Quest Site',type:'quest',icon:'◆',x:3,y:3,quest:true,desc:`A lead connected to ${q.title} points directly to this part of the district.`});
  return a
}
function selectHotspot55(id){ensurePhase56State();let sk=sceneKey55();if(!mapNodes55().some(n=>n.id===id))return;S.world.explore56.currentHotspot[sk]=id;S.world.explore56.mapNotice='';renderExplore52()}
function hiddenSearch55(){ensurePhase56State();let E=S.world.explore56,sk=sceneKey55();if(E.discovered[sk]){E.mapNotice='The hidden access has already been exposed.';renderExplore52();return}let skill=hotspotSkill55('hidden'),out=performBest(skill,{diff:hotspotDiff55('hidden'),setback:localHeat50()>=7?1:0});if(out.r.ok){E.discovered[sk]=true;E.currentHotspot[sk]='hidden';E.mapNotice=`${out.q.actor.name} finds a concealed access panel. A hidden room is now available on the local map.`;exploreLog52(E.mapNotice)}else{S.strain=Math.min(strainThreshold(),S.strain+1);E.mapNotice=`${out.q.actor.name} misses the hidden access and suffers 1 strain from the search.`}renderAll();renderNavTab('explore');safeAutosave()}
function lootReward55(hidden=false){let d=currentDistrict52(),base=(hidden?55:30)+d.diff*15,bonus=Math.floor(Math.random()*26),c=base+bonus;S.credits+=c;ledgerEntry(c,`${hidden?'Hidden cache':'Local container'} — ${currentScene53().name}`);let extra='';if(hidden&&Math.random()<.6){if(Math.random()<.5){S.stimpacks=(S.stimpacks||0)+1;extra=' and 1 stimpack'}else{S.reloads=(S.reloads||0)+1;extra=' and 1 reload'}}return`${c} credits${extra}`}
function hotspotAction55(id){
  ensurePhase56State();let E=S.world.explore56,sk=sceneKey55(),node=mapNodes55().find(n=>n.id===id);if(!node)return;
  if(id==='entry'){E.mapNotice='This is the crew’s current entry point. Use the scene path above to move to another part of the district.';renderExplore52();return}
  if(id==='terminal'){
    if(E.terminals[sk]){E.mapNotice='This terminal has already been exploited.';renderExplore52();return}
    let out=performBest('Computers',{diff:hotspotDiff55('terminal'),setback:localHeat50()>=7?1:0});if(out.r.ok){E.terminals[sk]=true;S.ep15.intel=(S.ep15.intel||0)+1;if(out.r.na>=2){S.world.sectorHeat[S.world.currentHub]=Math.max(0,localHeat50()-1);E.mapNotice=`${out.q.actor.name} pulls useful records and loops part of the local surveillance net. +1 Intel; local heat -1.`}else E.mapNotice=`${out.q.actor.name} extracts useful local records. +1 Intel.`;if(out.r.na>=1)E.discovered[sk]=true;exploreLog52(E.mapNotice)}else{S.strain=Math.min(strainThreshold(),S.strain+1);if(out.r.nt>=2)adjustHeat50(1,'a failed terminal intrusion leaves a trace');E.mapNotice='The terminal rejects the intrusion. The PC suffers 1 strain.'}renderAll();renderNavTab('explore');safeAutosave();return
  }
  if(id==='container'){
    let lk=`${sk}:container`;if(E.looted[lk]){E.mapNotice='The container has already been picked clean.';renderExplore52();return}let skill=hotspotSkill55('container'),out=performBest(skill,{diff:hotspotDiff55('container')});if(out.r.ok){E.looted[lk]=true;E.mapNotice=`${out.q.actor.name} opens the container and recovers ${lootReward55(false)}.`;exploreLog52(E.mapNotice)}else{S.strain=Math.min(strainThreshold(),S.strain+1);E.mapNotice='The container stays shut. The PC suffers 1 strain and can try again later.'}renderAll();renderNavTab('explore');safeAutosave();return
  }
  if(id==='environment'){
    if(E.environment[sk]){E.mapNotice='The crew has already prepared this environmental advantage.';renderExplore52();return}let skill=hotspotSkill55('environment'),out=performBest(skill,{diff:Math.max(1,hotspotDiff55('environment')-1)});if(out.r.ok){E.environment[sk]=true;E.mapNotice=`${out.q.actor.name} identifies a usable advantage in the environment. The next scripted scene check here is one step easier.`;exploreLog52(E.mapNotice)}else{S.strain=Math.min(strainThreshold(),S.strain+1);E.mapNotice='The feature offers no safe advantage. The PC suffers 1 strain.'}renderAll();renderNavTab('explore');safeAutosave();return
  }
  if(id==='door'){
    let lk=`${sk}:door`;if(E.unlocked[lk]||(!node.locked&&E.unlocked[lk])){if(!E.looted[`${sk}:doorroom`]){E.looted[`${sk}:doorroom`]=true;E.mapNotice=`The crew searches the secured back room and recovers ${lootReward55(true)}.`;exploreLog52(E.mapNotice)}else E.mapNotice='The secured back room has already been searched.';renderAll();renderNavTab('explore');safeAutosave();return}
    let skill=hotspotSkill55('door'),out=performBest(skill,{diff:hotspotDiff55('door'),setback:localHeat50()>=7?1:0});if(out.r.ok){E.unlocked[lk]=true;if(routeRequiresUnlock55()&&currentScene53().id==='s1')E.unlocked[routeKey55()]=true;E.mapNotice=`${out.q.actor.name} opens the secured route${routeRequiresUnlock55()&&currentScene53().id==='s1'?', unlocking access to the district’s deeper scene':''}.`;exploreLog52(E.mapNotice)}else{S.strain=Math.min(strainThreshold(),S.strain+1);if(out.r.nt>=2)adjustHeat50(1,'tampering with a secured door draws attention');E.mapNotice='The lock holds. The PC suffers 1 strain.'}renderAll();renderNavTab('explore');safeAutosave();return
  }
  if(id==='hidden'){
    let lk=`${sk}:hidden`;if(E.looted[lk]){E.mapNotice='The hidden room has already been searched.';renderExplore52();return}E.looted[lk]=true;S.ep15.intel=(S.ep15.intel||0)+1;E.mapNotice=`Inside the hidden room the crew recovers ${lootReward55(true)} and +1 Intel.`;exploreLog52(E.mapNotice);renderAll();renderNavTab('explore');safeAutosave();return
  }
  if(id==='quest'){
    let q=currentActiveQuest56();if(!q){E.mapNotice='The quest lead is no longer active.';renderExplore52();return}advanceQuest54(q.id);return
  }
}
function hotspotButtonLabel55(n){if(n.id==='entry')return'Inspect Entry';if(n.id==='terminal')return n.done?'Terminal Used':'Access Terminal';if(n.id==='container')return n.done?'Container Empty':'Open Container';if(n.id==='environment')return n.done?'Prepared':'Use Environment';if(n.id==='door')return n.locked?'Unlock Door':n.done?'Search Back Room':'Open Secured Door';if(n.id==='hidden')return n.done?'Hidden Room Searched':'Search Hidden Room';if(n.id==='quest')return'Advance Quest';return'Interact'}
function renderLocalMap55(){
  let root=$('localMap55');if(!root)return;ensurePhase56State();let E=S.world.explore56,sk=sceneKey55(),nodes=mapNodes55(),cur=E.currentHotspot[sk];if(!nodes.some(n=>n.id===cur))cur=E.currentHotspot[sk]='entry';let n=nodes.find(x=>x.id===cur),q=currentActiveQuest56();
  root.innerHTML=`<div class="row"><div><b>Local Area Map</b><div class="small">Move around the current scene and interact with terminals, containers, doors, environmental objects, hidden rooms, and quest sites.</div></div><span class="tag">PHASE 55</span></div><div class="local-map-grid55" style="margin-top:10px">${nodes.map(x=>`<button class="map-node55 ${x.id===cur?'current':''} ${x.done?'done':''} ${x.locked?'locked':''} ${x.hidden?'hidden-node':''} ${x.quest?'quest-node':''}" style="grid-column:${x.x};grid-row:${x.y}" data-hotspot55="${x.id}" ${x.locked?'aria-label="Locked access"':''} ${x.hidden?'data-hidden="true"':''}><span class="map-state55">${x.quest?'QUEST':x.locked?'LOCKED':x.done?'USED':''}</span><b><span class="map-icon55">${x.icon}</span>${opEsc(x.name)}</b><div class="tiny">${x.type==='quest'?opEsc(q?.title||'Active quest'):opEsc(hotspotSkill55(x.type))}</div></button>`).join('')}</div><div class="map-detail55"><div class="row"><div><b>${opEsc(n.name)}</b><div class="small">${opEsc(n.desc)}</div></div><button class="btn primary" id="hotspotAction55" ${n.done&&['terminal','environment'].includes(n.id)?'disabled':''}>${opEsc(hotspotButtonLabel55(n))}</button></div><div class="pills" style="margin-top:9px"><button class="btn" id="hiddenSearch55" ${E.discovered[sk]?'disabled':''}>${E.discovered[sk]?'Hidden Access Found':'Search for Hidden Access'}</button>${routeRequiresUnlock55()&&currentScene53().id==='s1'?`<span class="pill">Deep route: ${routeUnlocked55()?'OPEN':'LOCKED'}</span>`:''}</div>${E.mapNotice?`<div class="scene-notice54">${opEsc(E.mapNotice)}</div>`:''}</div><div class="map-legend55"><span>◎ entry</span><span>▣ terminal</span><span>▤ loot</span><span>▰ locked access</span><span>✦ hidden room</span><span>◆ quest site</span></div>`;
  root.querySelectorAll('[data-hotspot55]').forEach(b=>b.onclick=()=>selectHotspot55(b.dataset.hotspot55));$('hotspotAction55').onclick=()=>hotspotAction55(cur);$('hiddenSearch55').onclick=hiddenSearch55
}
function ensureLocalMapPanel55(){let nav=$('sceneNavigator53');if(!nav||$('localMap55'))return;let map=document.createElement('div');map.id='localMap55';map.className='local-map55';nav.appendChild(map)}

function scriptTemplate56(){
  let d=currentDistrict52(),kind=d.kind;
  if(['imperial','secure','spaceport','office'].includes(kind))return{id:'inspection',title:'Inspection Sweep',text:'A security team starts checking identities, cargo access, and reasons for being in the area.',choices:[['credentials','Show Credentials','Deception'],['talk','Talk Through It','Negotiation'],['slip','Slip Away','Stealth']]};
  if(['blackmarket','cantina','casino','underlevels','shadowport','waterfront'].includes(kind))return{id:'shakedown',title:'Territory Tax',text:'Local muscle decides your crew looks profitable enough to charge for the privilege of standing here.',choices:[['deal','Negotiate','Negotiation'],['pay','Pay 75 Credits',null],['refuse','Refuse','combat']]};
  if(['industrial','junkyard','market'].includes(kind))return{id:'failure',title:'System Failure',text:'A loader, power junction, or service unit fails violently enough to threaten nearby workers and cargo.',choices:[['repair','Stabilize It','Mechanics'],['reroute','Reroute Controls','Computers'],['leave','Keep Moving','Cool']]};
  if(['wilderness','outskirts'].includes(kind))return{id:'hazard',title:'Hazard Ahead',text:'Terrain, weather, or local wildlife turns a routine path into a dangerous decision.',choices:[['survive','Read the Terrain','Survival'],['push','Push Through','Athletics'],['avoid','Find Another Way','Perception']]};
  if(kind==='rebel')return{id:'compromise',title:'Compromised Contact',text:'A courier fails to give the expected recognition signal, and someone nearby may be watching.',choices:[['verify','Verify Quietly','Vigilance'],['cover','Create a Cover Story','Deception'],['trust','Trust the Contact','Cool']]};
  return{id:'disturbance',title:'Street Disturbance',text:'A tense argument is about to become everybody’s problem unless someone redirects it.',choices:[['calm','Defuse It','Charm'],['watch','Read the Crowd','Vigilance'],['leave','Stay Out of It','Cool']]}
}
function scriptState56(){ensurePhase56State();let sk=sceneKey55();return S.world.explore56.scripted[sk]||(S.world.explore56.scripted[sk]={started:false,resolved:false,choice:null,outcome:''})}
function scriptedDiff56(skill){let base=Math.max(1,currentScene53().diff),E=S.world.explore56;if(E.environment[sceneKey55()])base=Math.max(1,base-1);if(skill==='Stealth'||skill==='Deception')base+=localHeat50()>=7?1:0;return base}
function resolveScriptChoice56(choice){
  ensurePhase56State();let tpl=scriptTemplate56(),st=scriptState56(),ch=tpl.choices.find(x=>x[0]===choice);if(!ch||st.resolved)return;st.started=true;st.choice=choice;
  if(choice==='pay'){if(S.credits<75){st.outcome='You do not have 75 credits to buy your way out.';renderExplore52();return}S.credits-=75;ledgerEntry(-75,`Territory tax — ${currentScene53().name}`);st.resolved=true;st.outcome='The payment buys a quiet passage. The locals remember that you paid without making a scene.';adjustFactionRep('Local',1)}
  else if(ch[2]==='combat'){st.outcome='Words end. The confrontation turns violent.';S.world.explore56.pendingCombat={sceneKey:sceneKey55(),kind:'scripted56'};S.customEncounter=sceneAdversaries53();startCustomEncounter();safeAutosave();return}
  else{
    let out=performBest(ch[2],{diff:scriptedDiff56(ch[2])});if(out.r.ok){st.resolved=true;let intel=out.r.na>=2?1:0;if(intel)S.ep15.intel=(S.ep15.intel||0)+1;if(choice==='slip'||choice==='avoid')S.world.explore56.discovered[sceneKey55()]=true;if(choice==='repair'||choice==='reroute'){let c=30+currentDistrict52().diff*15;S.credits+=c;ledgerEntry(c,`Scene intervention — ${tpl.title}`);st.outcome=`${out.q.actor.name} handles the crisis cleanly and earns ${c} credits in gratitude/salvage${intel?' plus 1 Intel':''}.`}else if(choice==='credentials'||choice==='cover'){S.world.sectorHeat[S.world.currentHub]=Math.max(0,localHeat50()-1);st.outcome=`${out.q.actor.name} sells the explanation. Local heat falls by 1${intel?' and the crew gains 1 Intel':''}.`}else{adjustFactionRep(hub50().primaryFaction||'Local',1);st.outcome=`${out.q.actor.name} resolves the situation without violence. ${hub50().primaryFaction||'Local'} reputation +1${intel?' and +1 Intel':''}.`}}
    else{S.strain=Math.min(strainThreshold(),S.strain+1);if(out.r.nt>=2)adjustHeat50(1,`a failed choice during ${tpl.title}`);st.outcome=`${out.q.actor.name} fails the approach. The PC suffers 1 strain${out.r.nt>=2?' and local heat rises by 1':''}.`;if(['inspection','shakedown'].includes(tpl.id)&&out.r.nt>=2){S.world.explore56.pendingCombat={sceneKey:sceneKey55(),kind:'scripted56'};S.customEncounter=sceneAdversaries53();startCustomEncounter();safeAutosave();return}}
  }
  exploreLog52(`${tpl.title}: ${st.outcome}`);renderAll();renderNavTab('explore');safeAutosave()
}
function renderScripted56(){let box=$('scriptedScene56');if(!box)return;ensurePhase56State();let tpl=scriptTemplate56(),st=scriptState56();box.className=`scripted56 ${st.resolved?'resolved':''}`;box.innerHTML=`<div class="row"><div><b>${opEsc(tpl.title)}</b><div class="small">${opEsc(tpl.text)}</div></div><span class="tag">PHASE 56</span></div>${st.resolved?`<div class="scene-notice54">Resolved: ${opEsc(st.outcome)}</div>`:`<div class="script-choice56">${tpl.choices.map(c=>`<button class="btn" data-script56="${c[0]}"><b>${opEsc(c[1])}</b><div class="tiny">${c[2]===null?'Costs 75 credits':c[2]==='combat'?'Starts combat':`${opEsc(c[2])} ${acquisitionLabel(scriptedDiff56(c[2]))}`}</div></button>`).join('')}</div>${st.outcome?`<div class="scene-notice54">${opEsc(st.outcome)}</div>`:''}`}`;box.querySelectorAll('[data-script56]').forEach(b=>b.onclick=()=>resolveScriptChoice56(b.dataset.script56))}
function ensureScriptedPanel56(){let nav=$('sceneNavigator53');if(!nav||$('scriptedScene56'))return;let box=document.createElement('div');box.id='scriptedScene56';box.className='scripted56';nav.appendChild(box)}

function npcSnapshot56(id){let [hub,dist]=id.split(':');let d=(DISTRICTS_51[hub]||[]).find(x=>x.id===dist);if(!d)return null;let idx=Number((id.match(/npc(\d+)$/)||[])[1]);let a=d.npcs?.[idx];if(!a)return null;return{id,name:a[0],role:a[1],faction:a[2],skill:a[3],originDistrict:dist,hub}}
function syncNpcMoves56(){let E=S.world?.explore56;if(!E||!S.world?.explore54)return;for(let q of S.world.explore54.quests||[]){if(!q.giverId)continue;let st=E.npcStatus[q.giverId]||(E.npcStatus[q.giverId]={...(npcSnapshot56(q.giverId)||{}),movedTo:null,awayUntil:0});if(q.status==='active'&&q.step>=1)st.movedTo=q.target;else if(q.status==='complete')st.movedTo=st.originDistrict||null;else if(q.status==='offered')st.movedTo=st.originDistrict||null}}
const _p56NpcList=npcList52;npcList52=function(d=null){let base=_p56NpcList(d),E=S.world?.explore56;if(!E)return base;let cur=d||currentDistrict52(),day=S.world.day;base=base.filter(n=>{let st=E.npcStatus[n.id];if(!st)return true;if(st.awayUntil&&day<st.awayUntil)return false;if(st.movedTo&&st.movedTo!==cur.id)return false;return true});for(let [id,st] of Object.entries(E.npcStatus)){if(st.hub!==S.world.currentHub||st.originDistrict===cur.id||st.movedTo!==cur.id||(st.awayUntil&&day<st.awayUntil))continue;if(!base.some(n=>n.id===id))base.push({id,name:st.name,role:st.role,faction:st.faction,skill:st.skill})}return base};
function dialogueConsequence56(id,mode){ensurePhase56State();let E=S.world.explore56,n=npcList52().find(x=>x.id===id)||npcSnapshot56(id);if(!n)return;let st=E.npcStatus[id]||(E.npcStatus[id]={...(npcSnapshot56(id)||n),movedTo:null,awayUntil:0}),rec=E.dialogueChoices[id];if(rec?.resolved)return;let outcome='';if(mode==='help'){let out=performBest('Charm',{diff:Math.max(1,currentDistrict52().diff-1)});if(out.r.ok){addRelation54(id,1);adjustFactionRep(n.faction==='Local'?'Local':n.faction,1);E.discovered[sceneKey55()]=true;outcome=`${out.q.actor.name} offers useful help instead of asking for something. ${n.name} warms to the crew, and mentions a concealed access nearby.`}else{S.strain=Math.min(strainThreshold(),S.strain+1);outcome=`The offer comes across badly. The PC suffers 1 strain.`}}
  else if(mode==='press'){let out=performBest('Coercion',{diff:Math.max(2,currentDistrict52().diff)});addRelation54(id,-1);if(out.r.ok){S.ep15.intel=(S.ep15.intel||0)+2;outcome=`${out.q.actor.name} gets an answer the hard way. +2 Intel, but ${n.name} trusts the crew less.`}else{adjustHeat50(1,`pressuring ${n.name} too openly`);st.awayUntil=S.world.day+1;outcome=`${n.name} shuts the conversation down and disappears for the rest of the day. Local heat +1.`}}
  else if(mode==='pay'){if(S.credits<50){S.world.explore54.sceneNotice='You need 50 credits for a quiet information payment.';renderExplore52();return}S.credits-=50;ledgerEntry(-50,`Information payment — ${n.name}`);S.ep15.intel=(S.ep15.intel||0)+1;addRelation54(id,1);E.discovered[sceneKey55()]=true;outcome=`A discreet 50-credit payment buys +1 Intel and a useful hint about a hidden access route.`}
  E.dialogueChoices[id]={resolved:true,mode,outcome,day:S.world.day};S.world.explore54.sceneNotice=outcome;exploreLog52(`${n.name}: ${outcome}`);renderAll();renderNavTab('explore');safeAutosave()}
function renderDialogueConsequences56(){let box=$('npcDialogue52'),id=S.world.explore?.activeNpc;if(!box||!id)return;let n=npcList52().find(x=>x.id===id)||npcSnapshot56(id);if(!n)return;let rec=S.world.explore56.dialogueChoices[id];let wrap=document.createElement('div');wrap.className='dialogue-choice56';wrap.innerHTML=`<b>Choose your approach</b><div class="small">One consequential approach is remembered by this NPC.</div>${rec?.resolved?`<div class="scene-notice54">${opEsc(rec.outcome)}</div>`:`<div class="choice-grid56"><button class="btn" data-dialogchoice56="help"><b>Offer Help</b><div class="tiny">Charm · relationship/faction upside</div></button><button class="btn" data-dialogchoice56="press"><b>Press for Answers</b><div class="tiny">Coercion · more Intel, more risk</div></button><button class="btn" data-dialogchoice56="pay"><b>Pay for Information</b><div class="tiny">50 credits · discreet route</div></button></div>`}`;box.appendChild(wrap);wrap.querySelectorAll('[data-dialogchoice56]').forEach(b=>b.onclick=()=>dialogueConsequence56(id,b.dataset.dialogchoice56))}
function questOverlay56(){let q=currentActiveQuest56();if(!q)return'';let st=q.steps[q.step];return`<div class="quest-overlay56"><b>${opEsc(q.title)}</b><div class="small">This district is currently part of the quest. ${st?opEsc(st.label):'Return to the contact for resolution.'}</div></div>`}

const _p56VisitScene=visitScene53;visitScene53=function(id){ensurePhase56State();let cur=currentScene53();if(cur.id==='s1'&&id==='s2'&&routeRequiresUnlock55()&&!routeUnlocked55()){S.world.explore56.mapNotice='The route into the deeper scene is locked. Use the Secured Door hotspot on the local map.';S.world.explore54.sceneNotice=S.world.explore56.mapNotice;renderExplore52();return}_p56VisitScene(id);ensurePhase56State();S.world.explore56.currentHotspot[sceneKey55()]='entry';S.world.explore56.mapNotice='';renderExplore52()};
const _p56VisitDistrict=visitDistrict52;visitDistrict52=function(id){_p56VisitDistrict(id);ensurePhase56State();S.world.explore56.currentHotspot[sceneKey55()]='entry';S.world.explore56.mapNotice='';renderExplore52()};
const _p56AdvanceQuest=advanceQuest54;advanceQuest54=function(id){_p56AdvanceQuest(id);ensurePhase56State();syncNpcMoves56();renderExplore52()};
const _p56AcceptQuest=acceptQuest54;acceptQuest54=function(id){_p56AcceptQuest(id);ensurePhase56State();syncNpcMoves56();renderExplore52()};

const _p56RenderScene=renderSceneNavigator53;renderSceneNavigator53=function(){_p56RenderScene();ensurePhase56State();let view=$('sceneView53');if(view&&currentActiveQuest56())view.insertAdjacentHTML('beforeend',questOverlay56());if(routeRequiresUnlock55()&&currentScene53().id==='s1'&&!routeUnlocked55()&&view){view.insertAdjacentHTML('beforeend',`<div class="route-lock56"><div><b>Locked Deeper Route</b><div class="tiny">Open the Secured Door hotspot on the local map to reach scene 3.</div></div><span class="tag">LOCKED</span></div>`)}ensureLocalMapPanel55();renderLocalMap55();ensureScriptedPanel56();renderScripted56()};
const _p56RenderDialogue=renderDialogue54;renderDialogue54=function(){_p56RenderDialogue();ensurePhase56State();renderDialogueConsequences56()};
const _p56RenderExplore=renderExplore52;renderExplore52=function(){ensurePhase56State();_p56RenderExplore();ensureLocalMapPanel55();renderLocalMap55();ensureScriptedPanel56();renderScripted56();renderDialogueConsequences56()};
const _p56RenderAll=renderAll;renderAll=function(){_p56RenderAll();ensurePhase56State();if($('explore')&&!$('explore').classList.contains('hidden'))renderExplore52()};

const _p56CombatWin=combatWin;combatWin=function(){let p=S.world?.explore56?.pendingCombat?{...S.world.explore56.pendingCombat}:null,isCustom=S.combat?.kind==='customEncounter';let r=_p56CombatWin();if(isCustom&&p?.kind==='scripted56'){ensurePhase56State();S.world.explore56.pendingCombat=null;let st=S.world.explore56.scripted[p.sceneKey]||(S.world.explore56.scripted[p.sceneKey]={});st.resolved=true;st.outcome='The crew wins the confrontation and controls the scene.';let c=50+currentDistrict52().diff*20;S.credits+=c;ledgerEntry(c,'Scripted scene encounter');adjustFactionRep(hub50().primaryFaction||'Local',1);S.world.explore54.sceneNotice=`Scripted encounter resolved. +${c} credits and local reputation improves.`;exploreLog52(S.world.explore54.sceneNotice);renderAll();renderNavTab('explore');safeAutosave()}return r};

RULE_AUDIT.unshift(
 {id:'localmaps55',name:'Phase 55 local area maps and interactables',status:'adapted',source:'Original Sable Reach videogame layer on top of source-grounded districts',detail:'Terminals, containers, locked doors, hidden rooms, environmental preparation, quest-site markers, and room-level map movement are videogame abstractions rather than printed FFG subsystems.'},
 {id:'scripted56',name:'Phase 56 scripted scene choices and persistent NPC consequences',status:'adapted',source:'Original Sable Reach campaign layer',detail:'Scripted local dilemmas, consequential dialogue approaches, temporary NPC absence, quest-driven NPC movement, and district variants are original campaign systems using the existing FFG skill engine.'}
);
const _p56Diagnostics=phase45Diagnostics;phase45Diagnostics=function(){let rows=_p56Diagnostics().filter(x=>x.name!=='Save schema'&&x.name!=='Save serialization'&&!/Phase 54 save (schema|serialization)/.test(x.name));const add=(name,ok,detail='')=>rows.push({name,ok:!!ok,detail});ensurePhase56State();add('Phase 55 local-map interactables',mapNodes55().length>=5&&mapNodes55().some(x=>x.type==='terminal')&&mapNodes55().some(x=>x.type==='container'),'terminal/container/door/environment hotspots');add('Phase 55 hidden-room state',typeof S.world.explore56.discovered==='object'&&typeof S.world.explore56.looted==='object','persistent discovery and loot flags');add('Phase 56 scripted choices',scriptTemplate56().choices.length===3,'three approaches per scene event');add('Phase 56 NPC consequence state',typeof S.world.explore56.npcStatus==='object'&&typeof S.world.explore56.dialogueChoices==='object','movement/absence/dialogue memory');add('Phase 56 save schema',S.schemaVersion===56&&BUILD_INFO.saveSchema===56&&serializableState().schemaVersion===56,'schema 56');try{let x=JSON.parse(JSON.stringify(serializableState()));add('Phase 56 save serialization',x.schemaVersion===56&&typeof x==='object','JSON round-trip succeeded')}catch(e){add('Phase 56 save serialization',false,e.message)}return rows};
const _p56Smoke=runSableReachSmoke;runSableReachSmoke=async function(){let report=await _p56Smoke();report.failed=report.failed.filter(x=>!x.startsWith('build metadata:')&&!x.startsWith('startup guide exists:')&&!x.startsWith('Phase 43 campaign state initializes:')&&!/^Phase (45 schema migration target|46 schema target|48 schema target|50 schema target|52 schema target|54 schema target):/.test(x));const test=(name,fn)=>{try{if(fn()===false)throw new Error('returned false');report.passed.push(name)}catch(e){report.failed.push(`${name}: ${e.message}`)}};ensurePhase56State();test('Phase 55 local map renders five or more nodes',()=>{renderExplore52();return !!$('localMap55')&&$('localMap55').querySelectorAll('[data-hotspot55]').length>=5});test('Phase 55 terminal and container nodes exist',()=>{let a=mapNodes55();return a.some(x=>x.type==='terminal')&&a.some(x=>x.type==='container')});test('Phase 55 hidden room can be represented',()=>{let sk=sceneKey55(),old=S.world.explore56.discovered[sk];S.world.explore56.discovered[sk]=true;let ok=mapNodes55().some(x=>x.id==='hidden');S.world.explore56.discovered[sk]=old;return ok});test('Phase 56 scripted scene exposes three choices',()=>scriptTemplate56().choices.length===3);test('Phase 56 dialogue consequence memory exists',()=>typeof S.world.explore56.dialogueChoices==='object');test('Phase 56 schema target',()=>BUILD_INFO.saveSchema===56&&S.schemaVersion===56&&serializableState().schemaVersion===56);document.body.dataset.smokeStatus=report.failed.length?'FAIL':'PASS';document.body.dataset.smokePassed=String(report.passed.length);document.body.dataset.smokeFailed=String(report.failed.length);window.__SABLE_REACH_SMOKE__=report;let pre=$('smokeReport');if(pre)pre.textContent=JSON.stringify(report,null,2);return report};

const _p56Save=save;save=function(){_p56Save();bLog('Phase 56 local-map and scripted-scene state included in the current save slot.')};
ensurePhase56State();document.title='Star Wars: Sable Reach — Phase 56';renderAll();
window.__SABLE_REACH__={version:BUILD_INFO.version,diagnostics:()=>rcStateIssues(),smoke:runSableReachSmoke,state:()=>S};
