/* State regression tests, not a substitute for Safari/device layout QA. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const {createCanvas,Image}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../qa96');fs.mkdirSync(out,{recursive:true});
const errors=[],vc=new VirtualConsole(),surfaces=new WeakMap();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://felicianovalle-dev.github.io/swrpgtest/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
 w.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});
 w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};w.confirm=()=>true;w.alert=()=>{};
 w.HTMLCanvasElement.prototype.getContext=function(){let v=surfaces.get(this);if(!v){const cv=createCanvas(this.width||300,this.height||150),ctx=cv.getContext('2d'),draw=ctx.drawImage.bind(ctx);ctx.drawImage=(im,...args)=>{if(im instanceof w.HTMLCanvasElement){im.getContext('2d');im=surfaces.get(im).cv}return draw(im,...args)};v={cv,ctx};surfaces.set(this,v)}if(v.cv.width!==this.width)v.cv.width=this.width;if(v.cv.height!==this.height)v.cv.height=this.height;return v.ctx};
 w.HTMLCanvasElement.prototype.toDataURL=function(){this.getContext('2d');return surfaces.get(this).cv.toDataURL()};
 w.Image=function(){const im=new Image(),listeners={};im.addEventListener=(k,fn)=>{listeners[k]=fn;if(k==='load'&&im.complete)queueMicrotask(fn)};im.onload=()=>listeners.load?.();im.onerror=e=>listeners.error?.(e);Object.defineProperty(im,'naturalWidth',{get(){return im.width}});Object.defineProperty(im,'naturalHeight',{get(){return im.height}});return im};
}});
const w=dom.window,run=code=>w.eval(code),checks=[];
function check(name,fn){assert.ok(fn(),name);checks.push(name)}
function economicState(){return run('JSON.stringify({credits:S.credits,xp:S.earnedXp,skills:S.skills,training:S.training,worldDay:S.world.day,medicalDay:S.medical.day})')}
(async()=>{
 await new Promise(r=>setTimeout(r,1200));
 check('No boot/runtime errors',()=>errors.length===0&&w.document.getElementById('runtimeError').classList.contains('hidden'));
 check('Release version 96 with unchanged schema',()=>run("BUILD_INFO.version.startsWith('96.')&&serializableState().schemaVersion===92"));
 const original=run('JSON.stringify(serializableState())');
 run("S.finalized=false;openWorkHub96('jobs')");const creation=economicState();
 check('Unfinalized character cannot work',()=>run('workShift96()')===false&&economicState()===creation);
 check('Unfinalized character cannot practice',()=>run('practiceSkill96()')===false&&economicState()===creation);
 check('Unfinalized character cannot spend earned XP',()=>run('advanceSkill96()')===false&&economicState()===creation);
 run('S.finalized=true;S.combat={};');const combat=economicState();
 check('Combat blocks all downtime actions without mutation',()=>run('workShift96()===false&&practiceSkill96()===false&&advanceSkill96()===false')&&economicState()===combat);
 run('S.combat=null;S.dead=true');const dead=economicState();
 check('Incapacitated character cannot work or practice',()=>run('workShift96()===false&&practiceSkill96()===false')&&economicState()===dead);
 run('S.dead=false;S.wounds=0;S.strain=0;S.earnedXp=30;S.skills.Mechanics=0;S.training.skills.Mechanics={progress:0};ensureDowntime96();');
 const valid=economicState();
 check('Unknown skill IDs are rejected without mutation',()=>run("workShift96('bogus')===false&&practiceSkill96('bogus')===false&&advanceSkill96('bogus')===false")&&economicState()===valid);
 run('openWorkHub96("jobs");S.gmDestinyMode="off"');
 const liveWorkBefore=run('({day:S.world.day,shifts:S.downtime96.shifts})');
 w.document.getElementById('workShift96').click();
 check('Real paid-work button completes the unmocked dice flow',()=>run('S.downtime96.shifts')===liveWorkBefore.shifts+1&&run('S.world.day')===liveWorkBefore.day+1&&w.document.querySelector('.work-result96')?.textContent.includes('Shift complete'));
 run('openWorkHub96("training")');const livePracticeBefore=run('S.training.sessions');
 w.document.getElementById('practiceSkill96').click();
 check('Real practice button completes the unmocked dice flow',()=>run('S.training.sessions')===livePracticeBefore+1&&w.document.querySelector('.work-result96')?.textContent.includes('practice'));
 run('globalThis.realPerform96=performBest;globalThis.realRoll96=rollNarr;globalThis.realRandom96=Math.random;Math.random=()=>.9;performBest=()=>({q:{actor:actorById("pc")},r:{ok:true,ns:2,na:3,tr:0,de:0}});');
 const beforeWork=run('({cr:S.credits,xp:S.earnedXp,world:S.world.day,medical:S.medical.day,shifts:S.downtime96.shifts,skills:JSON.stringify(S.skills)})');
 const workResult=run('workShift96("Mechanics")');
 check('Successful work uses the original payout formula',()=>workResult.pay===155&&run('S.credits')===beforeWork.cr+155);
 check('A work shift advances each day counter exactly once',()=>run('S.world.day')===beforeWork.world+1&&run('S.medical.day')===beforeWork.medical+1);
 check('Working does not award XP or skill ranks',()=>run('S.earnedXp')===beforeWork.xp&&run('JSON.stringify(S.skills)')===beforeWork.skills);
 check('Work writes the ledger, activity result, and shift count',()=>run('S.downtime96.shifts')===beforeWork.shifts+1&&run('S.downtime96.history[0].text.includes("155 credits")')&&w.document.querySelector('.work-result96').textContent.includes('+155 Cr'));
 run('performBest=()=>({q:{actor:actorById("pc")},r:{ok:false,ns:-1,na:2,tr:0,de:0}})');
 const beforeFail=run('({cr:S.credits,day:S.world.day})');run('workShift96("Mechanics")');
 check('Failed work pays zero but consumes its disclosed day',()=>run('S.credits')===beforeFail.cr&&run('S.world.day')===beforeFail.day+1&&run('S.downtime96.history[0].text.includes("No payout")'));
 run('rollNarr=()=>({ok:true,ns:1,na:0,tr:0,de:0});S.training.skills.Mechanics={progress:0};S.skills.Mechanics=0');
 const beforeStudy=run('({cr:S.credits,xp:S.earnedXp,day:S.world.day,sessions:S.training.sessions})');
 run('practiceSkill96("Mechanics")');
 check('Practice keeps its first session progress',()=>run('S.training.skills.Mechanics.progress===1&&S.skills.Mechanics===0'));
 check('Practice costs a day, not credits or XP',()=>run('S.credits')===beforeStudy.cr&&run('S.earnedXp')===beforeStudy.xp&&run('S.world.day')===beforeStudy.day+1);
 run('practiceSkill96("Mechanics")');
 check('Practice improves a rank and deducts the target',()=>run('S.skills.Mechanics===1&&S.training.skills.Mechanics.progress===0&&S.training.sessions')===beforeStudy.sessions+2);
 run('rollNarr=()=>({ok:false,ns:-1,na:2,tr:0,de:0})');run('practiceSkill96("Mechanics")');
 check('Failed practice without 3 advantage grants no progress',()=>run('S.training.skills.Mechanics.progress')===0);
 run('rollNarr=()=>({ok:false,ns:-1,na:3,tr:0,de:0});practiceSkill96("Mechanics")');
 check('Failed practice with 3 advantage grants one progress',()=>run('S.training.skills.Mechanics.progress')===1);
 run('rollNarr=()=>({ok:true,ns:1,na:4,tr:1,de:0});S.training.skills.Mechanics.progress=2;practiceSkill96("Mechanics")');
 check('Advantage/triumph bonus and carryover are preserved',()=>run('S.skills.Mechanics===2&&S.training.skills.Mechanics.progress===3'));
 run('S.skills.Mechanics=4;S.training.skills.Mechanics.progress=5;rollNarr=()=>({ok:true,ns:1,na:0,tr:0,de:0});practiceSkill96("Mechanics")');
 check('Rank four can practice into rank five',()=>run('S.skills.Mechanics')===5);
 const cap=economicState();
 check('Rank five cap never spends XP or advances a day',()=>run('practiceSkill96("Mechanics")===false&&advanceSkill96("Mechanics")===false')&&economicState()===cap);
 run('S.skills.Mechanics=1;S.training.skills.Mechanics.progress=1;S.earnedXp=30');
 const cost=run('skillCost("Mechanics")'),xpBefore=run('({xp:S.earnedXp,cr:S.credits,day:S.world.day,medical:S.medical.day})');
 check('XP purchase succeeds using existing career cost',()=>run('advanceSkill96("Mechanics")')===true&&run('S.skills.Mechanics===2')&&run('S.earnedXp')===xpBefore.xp-cost);
 check('XP purchase leaves credits, day, and practice intact',()=>run('S.credits')===xpBefore.cr&&run('S.world.day')===xpBefore.day&&run('S.medical.day')===xpBefore.medical&&run('S.training.skills.Mechanics.progress')===1);
 run('S.earnedXp=0');const insufficient=economicState();
 check('Insufficient XP does not change state',()=>run('advanceSkill96("Mechanics")')===false&&economicState()===insufficient);
 run('performBest=realPerform96;rollNarr=realRoll96;Math.random=realRandom96;openWorkHub96("jobs")');
 w.document.querySelector('#mobileDock52 [data-workpanel96="training"]').click();
 check('Train dock opens the training panel, not Jobs',()=>run('S.downtime96.panel')==='training'&&!w.document.getElementById('trainingPanel96').hidden&&w.document.querySelectorAll('#mobileDock52 .on').length===1);
 w.document.querySelector('#mobileDock52 [data-workpanel96="jobs"]').click();
 check('Jobs dock opens the work panel',()=>run('S.downtime96.panel')==='jobs'&&!w.document.getElementById('jobsPanel96').hidden);
 run('renderNavTab("playhub80")');w.document.getElementById('hubTrain96').click();
 check('Play Hub exposes training directly',()=>!w.document.getElementById('worktraining96').classList.contains('hidden')&&run('S.downtime96.panel')==='training');
 run('renderNavTab("pixelworld67")');w.document.getElementById('worldMap94').click();w.document.getElementById('worldJobs96').click();
 check('World drawer exposes paid work directly',()=>!w.document.body.classList.contains('world-play94')&&run('S.downtime96.panel')==='jobs');
 run('pxSwitchMap67("sableTown")');
 check('Two kiosks are reachable without replacing an existing entity',()=>run('(()=>{let m=pixelCurrentMap67(),k=m.objects.filter(o=>/Kiosk96$/.test(o.id));return k.length===2&&k.every(o=>!m.npcs.some(n=>n.x===o.x&&n.y===o.y)&&pxFindPath67(m,pxPos67(),o,true).length>0)})()'));
 run('pxInteractObject67(pixelCurrentMap67().objects.find(o=>o.id==="trainingKiosk96"))');
 check('Training kiosk opens training',()=>run('S.downtime96.panel')==='training'&&!w.document.getElementById('worktraining96').classList.contains('hidden'));
 run('openVisualDialogue69(pixelCurrentMap67().npcs.find(n=>n.id==="n4-vi"))');w.document.getElementById('visualWork69').click();
 check('Ask About Work opens Jobs without leaving a dialogue overlay',()=>run('!PX67.dialog&&S.downtime96.panel==="jobs"')&&!w.document.getElementById('worktraining96').classList.contains('hidden'));
 run('renderNavTab("campaign");S.finalized=false');const legacy=economicState();
 check('Legacy paid-work and study buttons cannot bypass guards',()=>run('downtimeJob()===false&&studySkillSession()===false')&&economicState()===legacy);
 run('S.finalized=true;S.downtime96.studySkill="Medicine";S.downtime96.panel="training";S.training.skills.Medicine={progress:2};globalThis.roundTrip96=JSON.parse(JSON.stringify(serializableState()));S.downtime96=freshDowntime96();S.training.skills.Medicine.progress=0;hydrateState(roundTrip96,"test round trip")');
 check('Save import preserves selection, activity history, and practice',()=>run('S.downtime96.studySkill==="Medicine"&&S.downtime96.panel==="training"&&S.downtime96.history.length>0&&S.training.skills.Medicine.progress===2'));
 run(`globalThis.oldSave96=JSON.parse(${JSON.stringify(original)});delete oldSave96.downtime96;oldSave96.training={skills:{Mechanics:{progress:1}},sessions:8};hydrateState(oldSave96,"legacy schema92");`);
 check('Older saves initialize the new hub without losing old training',()=>run('S.downtime96.shifts===0&&S.downtime96.history.length===0&&S.training.skills.Mechanics.progress===1&&S.training.sessions===8'));
 check('Versioned PWA update does not change save keys',()=>fs.readFileSync(path.join(root,'sw.js'),'utf8').includes('phase96-jobs-mobile')&&run('serializableState().schemaVersion===92'));
 assert.deepEqual(errors,[]);const result={targeted:checks.length,checks,errors};fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));w.close();
})().catch(e=>{console.error(e);w.close();process.exit(1)});
