/* State regression tests, not a substitute for Safari/device layout QA. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const {createCanvas,Image}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../qa97');fs.mkdirSync(out,{recursive:true});
const errors=[],vc=new VirtualConsole(),surfaces=new WeakMap();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://felicianovalle-dev.github.io/swrpgtest/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
 w.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});
 w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};w.confirm=()=>true;w.alert=()=>{};
 w.HTMLCanvasElement.prototype.getContext=function(){let v=surfaces.get(this);if(!v){const cv=createCanvas(this.width||300,this.height||150),ctx=cv.getContext('2d'),draw=ctx.drawImage.bind(ctx);ctx.drawImage=(im,...args)=>{if(im instanceof w.HTMLCanvasElement){im.getContext('2d');im=surfaces.get(im).cv}return draw(im,...args)};v={cv,ctx};surfaces.set(this,v)}if(v.cv.width!==this.width)v.cv.width=this.width;if(v.cv.height!==this.height)v.cv.height=this.height;return v.ctx};
 w.HTMLCanvasElement.prototype.toDataURL=function(){this.getContext('2d');return surfaces.get(this).cv.toDataURL()};
 w.Image=function(){const im=new Image(),listeners={};im.addEventListener=(k,fn)=>{listeners[k]=fn;if(k==='load'&&im.complete)queueMicrotask(fn)};im.onload=()=>listeners.load?.();im.onerror=e=>listeners.error?.(e);Object.defineProperty(im,'naturalWidth',{get(){return im.width}});Object.defineProperty(im,'naturalHeight',{get(){return im.height}});return im};
}});
const w=dom.window,run=code=>w.eval(code),checks=[];
function check(name,fn){assert.ok(fn(),name);checks.push(name)}
function economicState(){return run('JSON.stringify({credits:S.credits,xp:S.earnedXp,skills:S.skills,training:S.training,worldDay:S.world.day,medicalDay:S.medical.day})')}
(async()=>{
 await new Promise(r=>setTimeout(r,1200));
 check('No startup errors with modular build',()=>errors.length===0&&w.document.getElementById('runtimeError').classList.contains('hidden'));
 run('S.finalized=true;S.wounds=0;S.strain=0;S.dead=false;');
 const original=run('JSON.parse(JSON.stringify(serializableState()))');
 const old={...original,lastSaved:'2026-10-01T10:00:00Z',credits:111,resume97:{screen:'equipment'}};
 const newer={...original,lastSaved:'2026-10-02T10:00:00Z',credits:222,resume97:{screen:'worktraining96',panel:'training'},saveInfo97:{savedAt:'2026-10-02T10:00:00Z',kind:'auto'}};
 w.localStorage.clear();w.localStorage.setItem(run('RC_SAVE_KEY'),JSON.stringify(old));w.localStorage.setItem(run('RC_AUTO_KEY'),JSON.stringify(newer));
 check('Resume latest chooses newer autosave over manual',()=>run('load()')===true&&run('S.credits')===222);
 check('Loaded continuation opens Training, not a guessed objective screen',()=>run('activeTabId78()')==='worktraining96'&&run('S.downtime96.panel')==='training');
 check('Loading a slot does not overwrite manual or auto',()=>JSON.parse(w.localStorage.getItem(run('RC_SAVE_KEY'))).credits===111&&JSON.parse(w.localStorage.getItem(run('RC_AUTO_KEY'))).credits===222);
 check('Explicit manual load remains separate from latest',()=>run('Game97.saves.loadSlot("manual")')===true&&run('S.credits')===111&&run('activeTabId78()')==='equipment');
 const broken={...newer,career:'unknown',saveInfo97:{savedAt:'2026-10-03T10:00:00Z'}};
 w.localStorage.setItem(run('RC_AUTO_KEY'),JSON.stringify(broken));
 check('Unreadable newest save is skipped in favor of a valid slot',()=>run('load()')===true&&run('S.credits')===111);
 run('Game97.saves.open()');
 check('Unreadable and legacy save status are visible',()=>w.document.getElementById('save97').textContent.includes('Unreadable save')&&w.document.getElementById('save97').textContent.includes('Legacy timestamp'));
 const before=economicState();
 check('Malformed import is rejected before changing campaign state',()=>{try{run('Game97.saves.apply({name:"broken"},"test import")')}catch{}return economicState()===before});
 const badForce={...newer,forceOwned:{Move:{bad:true}},saveInfo97:{savedAt:'2026-10-04T10:00:00Z'}};
 w.localStorage.setItem(run('RC_AUTO_KEY'),JSON.stringify(badForce));
 check('Malformed nested Force data is skipped before hydration',()=>run('load()')===true&&run('S.credits')===111);
 w.localStorage.setItem(run('RC_BACKUP_KEY'),JSON.stringify(newer));w.localStorage.setItem(run('RC_SAVE_KEY'),'{broken');
 run('save()');
 check('Saving over a corrupt manual slot preserves a readable backup',()=>JSON.parse(w.localStorage.getItem(run('RC_BACKUP_KEY'))).credits===222);
 w.localStorage.setItem(run('RC_SAVE_KEY'),JSON.stringify(old));
 run('renderNavTab("equipment");');run('save()');
 check('Manual save keeps the previous manual as backup',()=>JSON.parse(w.localStorage.getItem(run('RC_BACKUP_KEY'))).credits===111);
 const manual=JSON.parse(w.localStorage.getItem(run('RC_SAVE_KEY')));
 check('New save records slot, timestamp, and actual screen',()=>manual.saveInfo97.kind==='manual'&&Number.isFinite(Date.parse(manual.saveInfo97.savedAt))&&manual.resume97.screen==='equipment');
 run('S.credits=333;safeAutosave()');
 const autosave=JSON.parse(w.localStorage.getItem(run('RC_AUTO_KEY')));
 check('Autosave stamps its own write and leaves manual intact',()=>autosave.credits===333&&autosave.saveInfo97.kind==='auto'&&autosave.lastSaved===autosave.saveInfo97.savedAt&&JSON.parse(w.localStorage.getItem(run('RC_SAVE_KEY'))).credits===111);
 run('Game97.saves.open()');
 check('Save screen exposes latest, manual, backup, export, and import',()=>['resumeLatest97','manualSave97','exportSave97','importSave97'].every(id=>!!w.document.getElementById(id))&&!!w.document.querySelector('[data-loadslot97="backup"]'));
 const realSet=w.Storage.prototype.setItem;w.Storage.prototype.setItem=function(){throw new Error('test quota exhausted')};
 check('Failed writes return false and display failure, not Saved',()=>run('save()')===false&&w.document.getElementById('save97').textContent.includes('failed: test quota exhausted')&&w.document.getElementById('saveStatus').textContent==='Save needs attention');
 w.Storage.prototype.setItem=realSet;
 const oldWithoutResume={...original};delete oldWithoutResume.resume97;delete oldWithoutResume.saveInfo97;
 run(`Game97.saves.apply(${JSON.stringify(oldWithoutResume)},"older campaign")`);
 check('Older save does not inherit a different campaign continuation',()=>run('S.resume97')===null&&run('activeTabId78()')==='playhub80');
 run('S.resume97={screen:"does-not-exist"};');
 check('Unavailable continuation falls back to Play Hub',()=>run('Game97.resume.current()')==='playhub80');
 run('S.finalized=false;S.resume97=null');
 check('Creation without saved continuation opens character guide',()=>run('Game97.resume.current()')==='guide');
 run('S.finalized=true;S.combat={};S.resume97={screen:"equipment"}');
 check('Active combat takes precedence over a downtime screen',()=>run('Game97.resume.current()')==='combat');
 run('S.combat=null;pxSwitchMap67("cantinaInterior");renderNavTab("pixelworld67");pxPos67().x=16;pxPos67().y=18;save()');
 const worldSave=JSON.parse(w.localStorage.getItem(run('RC_SAVE_KEY')));
 run('pxSwitchMap67("sableTown");pxPos67().x=23;pxPos67().y=15');
 run(`Game97.saves.apply(${JSON.stringify(worldSave)},"world test")`);
 check('World resume restores map and position from saved campaign',()=>run('pixelCurrentMap67().id')==='cantinaInterior'&&run('pxPos67().x')===16&&run('pxPos67().y')===18&&run('activeTabId78()')==='pixelworld67');
 const outcome=economicState();
 run('pxDraw67();fitWorld94();Game97.resume.current()');
 check('Visual redraw and continuation do not change economy or skills',()=>economicState()===outcome);
 check('New visual material cache renders connected floors',()=>run('Game97.visual.tiles.size')>0);
 run('renderNavTab("pixelworld67");');w.document.getElementById('worldSave94').click();
 check('World Saves button opens slot choices',()=>run('activeTabId78()')==='save97');
 check('The original save namespace and schema remain intact',()=>run("RC_SAVE_KEY==='swrpg-phase92'&&serializableState().schemaVersion===92"));
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({targeted:checks.length,checks,errors},null,2));
 console.log(JSON.stringify({targeted:checks.length,checks,errors},null,2));w.close();
})().catch(error=>{console.error(error);w.close();process.exit(1)});
